<a href="https://colab.research.google.com/github/electronicvan/BT4222_FinalProject_GoodreadsRecommender/blob/main/03_Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This notebook is used for Feature Engineering,

<h1> Baseline Feature Set </h1>

## Core IDs

- `user_id`  
  Unique identifier of the user associated with the event row.

- `book_id`  
  Unique identifier of the book associated with the event row.


## Temporal Tracking

- `event_time`  
  Primary event timestamp for the row, based on `date_added`, used to order interactions chronologically and enforce temporal feature construction.


## Static Item Metadata

- `title`  
  Raw book title.

- `description_truncated`  
  Truncated version of description, created to provide a more controlled text input for semantic encoding while limiting the influence of unusually long or noisy descriptions (cut off at 286 words)

- `top_shelf_tags`  
  Top cleaned informative shelf tags extracted from `popular_shelves` after excluding administrative, ownership, platform, and other non-content shelves.

- `has_meaningful_description`  
  Flag indicating whether the description passed the text-quality check and is considered sufficiently informative for downstream semantic use.

- `publication_year`  
  Publication year of the book.

- `num_pages`  
  Number of pages in the book.

- `language_code_collapsed`  
  Cleaned/collapsed language category for the book.

- `format_collapsed`  
  Cleaned/collapsed book format category.

- `is_ebook`  
  Indicator of whether the book is an ebook.

- `main_author_id`  
  Primary creator identifier used for author-based features. Preferably the first contributor with standardized role `author`; otherwise falls back to the first available contributor ID.

- `item_semantic_embedding_static`  
  Dense embedding from SentenceTransformer all-MiniLM-L6-v2, normalized.


## User-History / Matching features

- `num_pages_preference_gap`  
  Absolute difference between the current book's num_pages and the user's average num_pages of books in the user's prior interaction history before t. (user_page_preference_before_t)

- `user_author_interaction_share_before_t`
  Proportion of the user’s prior interactions before event time t, that involved the same main_author_id as the current book.

- `user_profile_embedding_similarity`
  Cosine similarity of the candidate book compared to the user’s prior semantic taste, quantified by user_profile_embedding_before_t


## Item Temporal Popularity

- `book_ratings_count_before_t`  
  Number of prior explicit ratings observed for the book before the current event time.

- `book_average_rating_before_t`  
  Average of prior explicit ratings observed for the book before the current event time.

## User Activity History

- `user_hist_interaction_count_before_t`
  Total number of interactions the user had before t. Basis for dense (>= 5) vs. sparse (< 5) user segmentation used in performance analysis.

- `user_hist_author_diversity_before_t`
  Count of distinct main_author_id values in the user's prior interaction history before t. Captures reading breadth.

- `days_since_user_last_interaction`
  Number of days between the last observed interaction of user and event time t.

<h1> Import Statements & Sample Rows of original dataframes </h1>

In [ ]:
import pandas as pd
from collections import Counter
import ast

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
books_df_cleaned = pd.read_csv("/content/drive/MyDrive/BT4222Project/CleanedDatasets/books_df_cleaned.csv")
reviews_df_cleaned = pd.read_csv("/content/drive/MyDrive/BT4222Project/CleanedDatasets/reviews_df_cleaned.csv")
interactions_df_cleaned = pd.read_csv("/content/drive/MyDrive/BT4222Project/CleanedDatasets/interactions_df_cleaned.csv")

In [ ]:
print("\nSample row from books_df_cleaned:")
display(books_df_cleaned.head(1).T)

print("\nSample row from interactions_df_cleaned:")
display(interactions_df_cleaned.head(1).T)

print("\nSample row from reviews_df_cleaned:")
display(reviews_df_cleaned.head(1).T)

Sample row from books_df_cleaned:

                                                                            0
isbn                                                               1599150603
text_reviews_count                                                          7
series                                                                     []
country_code                                                               US
language_code                                                             NaN
popular_shelves             [{'count': '56', 'name': 'to-read'}, {'count':...
is_ebook                                                                False
average_rating                                                           4.13
similar_books                                                              []
description                 Relates in vigorous prose the tale of Aeneas, ...
format                                                              Paperback
link                        https://www.goodreads.com/book/show/287141.The...
authors                                [{'author_id': '3041852', 'role': ''}]
publisher                                                Yesterday's Classics
num_pages                                                               162.0
publication_day                                                          13.0
isbn13                                                          9781599150604
publication_month                                                         9.0
publication_year                                                       2006.0
book_id                                                                287141
ratings_count                                                              46
title                                           The Aeneid for Boys and Girls
title_without_series                            The Aeneid for Boys and Girls
language_code_missing                                                       1
language_code_collapsed                                               unknown
format_collapsed                                                    paperback
authors_standardized        [{'author_id': '3041852', 'role_standardized':...
description_word_count                                                     55
has_meaningful_description                                                  1
is_long_description                                                         0
description_truncated       Relates in vigorous prose the tale of Aeneas, ...

Sample row from interactions_df_cleaned:

                                                0
user_id          8842281e1d1347389f2ab93d60773d4d
book_id                                  10893214
review_id        5d0e4e8825c68740703f65a18813fc93
is_read                                     False
rating                                          0
date_added              2017-02-24 17:00:30+00:00
date_updated            2017-02-24 17:00:30+00:00
read_at                                       NaN
started_at                                    NaN
has_rating                                      0
cleaned_rating                                  0
positive_rating                                 0

Sample row from reviews_df_cleaned:

                                                           0
user_id                     8842281e1d1347389f2ab93d60773d4d
book_id                                             23310161
review_id                   f4b4b050f4be00e9283c92a814af2670
rating                                                     4
review_text                      Fun sequel to the original.
date_added                         2015-11-17 19:37:35+00:00
date_updated                       2015-11-17 19:38:05+00:00
read_at                                                  NaN
started_at                                               NaN
n_votes                                                  7.0
n_comments                                               0.0
has_rating                                                 1
cleaned_rating                                             4
positive_rating                                            1
has_usable_review_text                                     1
has_meaningful_review_text                                 1

<h1> Building Baseline Feature Set </h1>

In [ ]:
print(f"Cols in Books df: {books_df_cleaned.columns}")
print(f"Cols in Interactions df: {interactions_df_cleaned.columns}")
print(f"Cols in Reviews df: {reviews_df_cleaned.columns}")

Cols in Books df: Index(['isbn', 'text_reviews_count', 'series', 'country_code', 'language_code',
       'popular_shelves', 'is_ebook', 'average_rating', 'similar_books',
       'description', 'format', 'link', 'authors', 'publisher', 'num_pages',
       'publication_day', 'isbn13', 'publication_month', 'publication_year',
       'book_id', 'ratings_count', 'title', 'title_without_series',
       'language_code_missing', 'language_code_collapsed', 'format_collapsed',
       'authors_standardized', 'description_word_count',
       'has_meaningful_description', 'is_long_description',
       'description_truncated'],
      dtype='object')
Cols in Interactions df: Index(['user_id', 'book_id', 'review_id', 'is_read', 'rating', 'date_added',
       'date_updated', 'read_at', 'started_at', 'has_rating', 'cleaned_rating',
       'positive_rating'],
      dtype='object')
Cols in Reviews df: Index(['user_id', 'book_id', 'review_id', 'rating', 'review_text',
       'date_added', 'date_updated', 'read_at', 'started_at', 'n_votes',
       'n_comments', 'has_rating', 'cleaned_rating', 'positive_rating',
       'has_usable_review_text', 'has_meaningful_review_text'],
      dtype='object')

In [ ]:
## Create static item table

items_static_cols = [
    "book_id",
    "title",
    "description",
    "description_truncated",
    "has_meaningful_description",
    "publication_year",
    "num_pages",
    "language_code_collapsed",
    "language_code_missing",
    "format_collapsed",
    "is_ebook",
    "authors_standardized",
    "popular_shelves",
    "ratings_count",
    "average_rating",
]

items_static_cols = [c for c in items_static_cols if c in books_df_cleaned.columns]

items_static_df = books_df_cleaned[items_static_cols].copy()

print(items_static_df.shape)
items_static_df.head()

(124037, 15)

,book_id,title,description,description_truncated,has_meaningful_description,publication_year,num_pages,language_code_collapsed,language_code_missing,format_collapsed,is_ebook,authors_standardized,popular_shelves,ratings_count,average_rating
0,287141,The Aeneid for Boys and Girls,"Relates in vigorous prose the tale of Aeneas, ...","Relates in vigorous prose the tale of Aeneas, ...",1,2006.0,162.0,unknown,1,paperback,False,"[{'author_id': '3041852', 'role_standardized':...","[{'count': '56', 'name': 'to-read'}, {'count':...",46,4.13
1,6066812,All's Fairy in Love and War (Avalon: Web of Ma...,"To Kara's astonishment, she discovers that a p...","To Kara's astonishment, she discovers that a p...",1,2009.0,216.0,unknown,1,paperback,False,"[{'author_id': '19158', 'role_standardized': '...","[{'count': '515', 'name': 'to-read'}, {'count'...",98,4.22
2,89378,Dog Heaven,In Newbery Medalist Cynthia Rylant's classic b...,In Newbery Medalist Cynthia Rylant's classic b...,1,1995.0,40.0,english,0,hardcover,False,"[{'author_id': '5411', 'role_standardized': 'a...","[{'count': '450', 'name': 'to-read'}, {'count'...",1331,4.43
3,3209312,"Moths and Mothers, Feathers and Fathers: A Sto...",NaN,NaN,0,NaN,NaN,unknown,1,unknown,False,"[{'author_id': '589328', 'role_standardized': ...","[{'count': '8', 'name': 'to-read'}, {'count': ...",11,4.29
4,1698376,What Do You Do?,WHAT DO YOU DO?\nA hen lays eggs...\nA cow giv...,WHAT DO YOU DO? A hen lays eggs... A cow gives...,1,2005.0,24.0,unknown,1,board_book,False,"[{'author_id': '169159', 'role_standardized': ...","[{'count': '8', 'name': 'to-read'}, {'count': ...",23,3.57

In [ ]:
## Create the event table from interactions

events_df = interactions_df_cleaned.copy()

# Use date_added as the primary event timestamp
events_df = events_df.rename(columns={"date_added": "event_time"})

event_cols = [
    "user_id",
    "book_id",
    "review_id",
    "event_time"
]

event_cols = [c for c in event_cols if c in events_df.columns]
events_df = events_df[event_cols].copy()

# Sort chronologically for later history features
events_df = events_df.sort_values(["user_id", "event_time", "book_id"]).reset_index(drop=True)

print(events_df.shape)
events_df.head()

(8770364, 4)

,user_id,book_id,review_id,event_time
0,00000377eea48021d3002730d56aca9a,13023,b5c7c0ca89779a65111ae924633ecf38,2014-12-07 20:11:06+00:00
1,00000377eea48021d3002730d56aca9a,41684,1d73829a06fe385376ecee3c29cb8be6,2014-12-07 20:13:38+00:00
2,00000377eea48021d3002730d56aca9a,34268,b521eeebe231b781e7176f35a8006cb4,2014-12-07 20:14:28+00:00
3,00000377eea48021d3002730d56aca9a,3636,fb806519c054c34a2c67b02ffc9fbb22,2014-12-07 20:15:18+00:00
4,00000377eea48021d3002730d56aca9a,152380,e8bc34e625167d545dc0ad2550e8aca9,2016-01-21 11:41:35+00:00

In [ ]:
## Merge static item features into events

baseline_df = events_df.merge(
    items_static_df,
    on="book_id",
    how="left",
    validate="many_to_one"
)

print(baseline_df.shape)
baseline_df.head()

(8770364, 18)

,user_id,book_id,review_id,event_time,title,description,description_truncated,has_meaningful_description,publication_year,num_pages,language_code_collapsed,language_code_missing,format_collapsed,is_ebook,authors_standardized,popular_shelves,ratings_count,average_rating
0,00000377eea48021d3002730d56aca9a,13023,b5c7c0ca89779a65111ae924633ecf38,2014-12-07 20:11:06+00:00,Alice in Wonderland,This is an adaptation. For the editions of the...,This is an adaptation. For the editions of the...,1,2004.0,92.0,english,0,hardcover,False,"[{'author_id': '34933', 'role_standardized': '...","[{'count': '140329', 'name': 'to-read'}, {'cou...",346530,4.03
1,00000377eea48021d3002730d56aca9a,41684,1d73829a06fe385376ecee3c29cb8be6,2014-12-07 20:13:38+00:00,The Jungle Books,The Jungle Books can be regarded as classic st...,The Jungle Books can be regarded as classic st...,1,2005.0,368.0,english,0,paperback,False,"[{'author_id': '6989', 'role_standardized': 'a...","[{'count': '1555', 'name': 'classics'}, {'coun...",69923,4.01
2,00000377eea48021d3002730d56aca9a,34268,b521eeebe231b781e7176f35a8006cb4,2014-12-07 20:14:28+00:00,Peter Pan,"Peter Pan, the book based on J.M. Barrie's fam...","Peter Pan, the book based on J.M. Barrie's fam...",1,NaN,NaN,english,0,unknown,False,"[{'author_id': '5255014', 'role_standardized':...","[{'count': '116674', 'name': 'to-read'}, {'cou...",173396,4.10
3,00000377eea48021d3002730d56aca9a,3636,fb806519c054c34a2c67b02ffc9fbb22,2014-12-07 20:15:18+00:00,"The Giver (The Giver, #1)",Twelve-year-old Jonas lives in a seemingly ide...,Twelve-year-old Jonas lives in a seemingly ide...,1,2006.0,208.0,english,0,paperback,False,"[{'author_id': '2493', 'role_standardized': 'a...","[{'count': '13366', 'name': 'to-read'}, {'coun...",1311422,4.12
4,00000377eea48021d3002730d56aca9a,152380,e8bc34e625167d545dc0ad2550e8aca9,2016-01-21 11:41:35+00:00,"Mary Poppins (Mary Poppins, #1)","By P.L. Travers, the author featured in the ma...","By P.L. Travers, the author featured in the ma...",1,2006.0,209.0,english,0,hardcover,False,"[{'author_id': '6872556', 'role_standardized':...","[{'count': '1938', 'name': 'to-read'}, {'count...",84109,4.05

In [ ]:
print(baseline_df.columns)

Index(['user_id', 'book_id', 'review_id', 'event_time', 'title', 'description',
       'description_truncated', 'has_meaningful_description',
       'publication_year', 'num_pages', 'language_code_collapsed',
       'language_code_missing', 'format_collapsed', 'is_ebook',
       'authors_standardized', 'popular_shelves', 'ratings_count',
       'average_rating'],
      dtype='object')

Item-Side Feature: Author
- main_author_id
- author_interactions_count_before_t

In [ ]:
# --------------------------------------------
# 1. Safely recreate main_author_id in books_df_cleaned
# --------------------------------------------
if "main_author_id" in books_df_cleaned.columns:
    books_df_cleaned = books_df_cleaned.drop(columns=["main_author_id"])

def get_main_author_id(authors_entry):
    if isinstance(authors_entry, str):
        try:
            authors_entry = ast.literal_eval(authors_entry)
        except Exception:
            return pd.NA

    if isinstance(authors_entry, dict):
        authors_entry = [authors_entry]

    if not isinstance(authors_entry, list):
        return pd.NA

    # First pass: prefer explicit author role
    for d in authors_entry:
        if isinstance(d, dict) and d.get("role_standardized") == "author":
            author_id = d.get("author_id")
            if pd.notna(author_id):
                return author_id

    # Fallback: first available author_id
    for d in authors_entry:
        if isinstance(d, dict):
            author_id = d.get("author_id")
            if pd.notna(author_id):
                return author_id

    return pd.NA

books_df_cleaned["main_author_id"] = books_df_cleaned["authors_standardized"].apply(
    get_main_author_id
)

# --------------------------------------------
# 2. Safely merge main_author_id into baseline_df
# --------------------------------------------
if "main_author_id" in baseline_df.columns:
    baseline_df = baseline_df.drop(columns=["main_author_id"])

baseline_df = baseline_df.merge(
    books_df_cleaned[["book_id", "main_author_id"]],
    on="book_id",
    how="left"
)

print(baseline_df[["book_id", "main_author_id"]].head(10))

num_valid = baseline_df["main_author_id"].notna().sum()
num_missing = baseline_df["main_author_id"].isna().sum()
total = len(baseline_df)

print(f"\nRows with valid main_author_id in baseline_df: {num_valid} ({num_valid / total:.2%})")
print(f"Rows with missing main_author_id in baseline_df: {num_missing} ({num_missing / total:.2%})")

    book_id main_author_id
0     13023           8164
1     41684           6989
2     34268        5255014
3      3636           2493
4    152380        6872556
5         5        1077326
6  27986676        2738670
7      3636           2493
8    357664          13663
9     38709           6569

Rows with valid main_author_id in baseline_df: 8770364 (100.00%)
Rows with missing main_author_id in baseline_df: 0 (0.00%)

In [ ]:
# --------------------------------------------
# Safely recreate author_interactions_count_before_t
# Count of prior interactions for the current row's main_author_id
# in strict event_time order. Starts at 0 for each author's
# first observed interaction.
# --------------------------------------------
if "author_interactions_count_before_t" in baseline_df.columns:
    baseline_df = baseline_df.drop(columns=["author_interactions_count_before_t"])

baseline_df = baseline_df.sort_values(
    ["event_time", "user_id", "book_id"]
).reset_index(drop=True)

baseline_df["author_interactions_count_before_t"] = (
    baseline_df.groupby("main_author_id").cumcount()
)

baseline_df.loc[
    baseline_df["main_author_id"].isna(),
    "author_interactions_count_before_t"
] = pd.NA

print(
    baseline_df[
        ["user_id", "book_id", "event_time", "main_author_id", "author_interactions_count_before_t"]
    ].head(20)
)

num_valid = baseline_df["author_interactions_count_before_t"].notna().sum()
num_missing = baseline_df["author_interactions_count_before_t"].isna().sum()
total = len(baseline_df)

print(f"\nRows with valid author_interactions_count_before_t: {num_valid} ({num_valid / total:.2%})")
print(f"Rows with missing author_interactions_count_before_t: {num_missing} ({num_missing / total:.2%})")

                             user_id  book_id                 event_time  \
0   dcdc48c7d14a6467cf277c9c0919eb02     6310  1990-01-01 08:00:00+00:00
1   dcdc48c7d14a6467cf277c9c0919eb02     6319  1990-01-01 08:00:00+00:00
2   dcdc48c7d14a6467cf277c9c0919eb02     6689  1990-01-01 08:00:00+00:00
3   dcdc48c7d14a6467cf277c9c0919eb02    10365  1990-01-01 08:00:00+00:00
4   dcdc48c7d14a6467cf277c9c0919eb02    39988  1990-01-01 08:00:00+00:00
5   dcdc48c7d14a6467cf277c9c0919eb02   385247  1990-01-01 08:00:00+00:00
6   dcdc48c7d14a6467cf277c9c0919eb02   108999  1992-01-01 08:00:00+00:00
7   dcdc48c7d14a6467cf277c9c0919eb02   299085  1992-01-01 08:00:00+00:00
8   dcdc48c7d14a6467cf277c9c0919eb02    24178  1992-03-29 08:00:00+00:00
9   dcdc48c7d14a6467cf277c9c0919eb02  1248471  1995-01-01 08:00:00+00:00
10  12707977a55df3ec3deaf86e874fe3ad   343114  1998-06-06 07:00:00+00:00
11  12707977a55df3ec3deaf86e874fe3ad   125518  1998-09-01 07:00:00+00:00
12  dd9db6365de817e4d5468394d8d03fa7  3131741  2000-07-01 07:00:00+00:00
13  12707977a55df3ec3deaf86e874fe3ad   297671  2000-08-15 07:00:00+00:00
14  12707977a55df3ec3deaf86e874fe3ad   438492  2001-02-02 08:00:00+00:00
15  e1e14dc7930a570911a031ca3d68b907     8127  2001-02-13 08:00:00+00:00
16  e1e14dc7930a570911a031ca3d68b907     8337  2001-02-13 08:00:00+00:00
17  e1e14dc7930a570911a031ca3d68b907    99107  2001-02-13 08:00:00+00:00
18  e1e14dc7930a570911a031ca3d68b907   125190  2001-02-13 08:00:00+00:00
19  e1e14dc7930a570911a031ca3d68b907   662786  2001-02-13 08:00:00+00:00

   main_author_id  author_interactions_count_before_t
0            4273                                 0.0
1            4273                                 1.0
2            4273                                 2.0
3            6810                                 0.0
4            4273                                 3.0
5            4273                                 4.0
6            4273                                 5.0
7           10087                                 0.0
8          988142                                 0.0
9           11633                                 0.0
10          81466                                 0.0
11          27318                                 0.0
12         410653                                 0.0
13          36746                                 0.0
14          36746                                 1.0
15           5350                                 0.0
16           5300                                 0.0
17          81466                                 1.0
18          72120                                 0.0
19         355881                                 0.0

Rows with valid author_interactions_count_before_t: 8770364 (100.00%)
Rows with missing author_interactions_count_before_t: 0 (0.00%)

Item-Side Feature: Shelf Tags
- top_shelf_tags

In [ ]:
# --- Print unique shelf names from popular_shelves with counts and percentages ---
def parse_shelves_entry(entry):
    """Safely parse the popular_shelves entry into a list of dicts."""
    if entry is None:
        return []
    if isinstance(entry, list):
        return entry
    if isinstance(entry, dict):
        return [entry]
    if isinstance(entry, str):
        entry = entry.strip()
        if not entry:
            return []
        try:
            obj = ast.literal_eval(entry)
            if isinstance(obj, dict):
                return [obj]
            if isinstance(obj, list):
                return obj
        except Exception:
            pass
    return []

def get_all_shelf_names(entry):
    names = []
    parsed = parse_shelves_entry(entry)
    for d in parsed:
        if isinstance(d, dict) and 'name' in d:
            name = str(d['name']).strip().lower()
            names.append(name)
    return names

from collections import Counter
all_shelf_names = []
for entry in books_df_cleaned['popular_shelves']:
    all_shelf_names.extend(get_all_shelf_names(entry))

shelf_counter = Counter(all_shelf_names)
total_books = len(books_df_cleaned)
print(f"Unique shelf names found: {len(shelf_counter)}\n")
print(f"{'Shelf Name':<30} {'Count':>8} {'% of books':>12}")
for name, count in shelf_counter.most_common():
    pct = count / total_books * 100
    print(f"{name:<30} {count:>8} {pct:>11.2f}%")

Streaming output truncated to the last 5000 lines.
juv-pic-bk-i-loved-zander-didn-t        1        0.00%
forts                                 1        0.00%
toby-grade-one                        1        0.00%
authors-in-classroom-library          1        0.00%
future-k                              1        0.00%
religion-spirituality-magic           1        0.00%
escrito-en-espanol                    1        0.00%
for-my-family                         1        0.00%
dominican-republic-santo-domingo        1        0.00%
good-translations                     1        0.00%
possible-bb                           1        0.00%
environmental-activism                1        0.00%
read-alouds-spring                    1        0.00%
read-with-myla                        1        0.00%
2017_reading_challenge                1        0.00%
lexie-books                           1        0.00%
yoko-tanaka-illustrator               1        0.00%
let-s-add-all-books                   1        0.00%
group-harlem                          1        0.00%
worldview-total-recall                1        0.00%
renaissance-in-harlem                 1        0.00%
wedding-recommendations               1        0.00%
what-s-it-saying                      1        0.00%
stately                               1        0.00%
yellowstone-park                      1        0.00%
comprehension-visualising             1        0.00%
jenny-s-picture-books                 1        0.00%
--41-                                 1        0.00%
books-with-addy                       1        0.00%
2017-ss                               1        0.00%
to-read-old                           1        0.00%
self-motivation                       1        0.00%
very-amusing                          1        0.00%
_part-of-a-series                     1        0.00%
lauren-easter                         1        0.00%
threadgould                           1        0.00%
crafts-cook                           1        0.00%
must-read-again-and-again             1        0.00%
to-readhome                           1        0.00%
2011-winter                           1        0.00%
non-fiction-crafts                    1        0.00%
scrapbooking-craft                    1        0.00%
first-nation-native-american          1        0.00%
zz-cover-element                      1        0.00%
zzcover-element                       1        0.00%
culturally-sensitive-thanksgiving        1        0.00%
native-americans-and-american-india        1        0.00%
golden-sower-award                    1        0.00%
love-that-ending-picture-bks          1        0.00%
je-monster-books                      1        0.00%
mystery-thriller-espionnage           1        0.00%
antiquity-ancient-times               1        0.00%
cned                                  1        0.00%
--254-                                1        0.00%
--526-                                1        0.00%
teach-concepts-with-this              1        0.00%
blog-to-review-red-blog               1        0.00%
modern-school-stories                 1        0.00%
have-to-do-it                         1        0.00%
boardingschool-college                1        0.00%
read-may-2015                         1        0.00%
terrific-twenty                       1        0.00%
children-s-books-inspired-by-real-l        1        0.00%
ua-lit                                1        0.00%
українська                            1        0.00%
2012-13-art                           1        0.00%
picture-book-intermediate             1        0.00%
fantasy-elementary                    1        0.00%
inner-beauty                          1        0.00%
comics-gn                             1        0.00%
kids--song-chant-rhyme                1        0.00%
grrl                                  1        0.00%
nonfiction-expository                 1        0.00%
lis-590-nfl                           1        0.00%
because-i-m-a-teacher                 1        0.00%
new-dimensions                        1        0.00%
books-that-were-ok                    1        0.00%
childrens-sci-fi-fantasy              1        0.00%
ought-to-remember                     1        0.00%
little-or-no-romance-books            1        0.00%
eighth-grade-books                    1        0.00%
drugs-and-the-stuff                   1        0.00%
books-i-ve-re-read-more-than-once        1        0.00%
podcast-reviewers-recommendations        1        0.00%
pic-books-weather                     1        0.00%
ffi                                   1        0.00%
age-1-4                               1        0.00%
earliest-times                        1        0.00%
history-and-co                        1        0.00%
started-reading-didnt-finish          1        0.00%
jesses-books                          1        0.00%
once-upon-a-slime                     1        0.00%
bodie-current-library-books           1        0.00%
orthodox-life                         1        0.00%
hs-health                             1        0.00%
sad-depressing-books                  1        0.00%
pilgrimage                            1        0.00%
mastering-basics-of-economic-princ        1        0.00%
econ                                  1        0.00%
business-management-etc               1        0.00%
suggestion-read                       1        0.00%
bahasa-melayu                         1        0.00%
kewangan                              1        0.00%
panduan                               1        0.00%
novel-grafik                          1        0.00%
hubbys-collection                     1        0.00%
owned-then-sold                       1        0.00%
business-motivation                   1        0.00%
investment                            1        0.00%
business-to-read                      1        0.00%
comic-and-manga                       1        0.00%
entreprenuership-business-investing        1        0.00%
mind-tricks                           1        0.00%
comic-crap                            1        0.00%
comic-children                        1        0.00%
aoibhin                               1        0.00%
remembrance-day-for-young-children        1        0.00%
books-that-megan-has-read             1        0.00%
family-mindfulness                    1        0.00%
theme---under-the-sea                 1        0.00%
children-n-fic                        1        0.00%
به-انگلیسی                            1        0.00%
owned-a-physical-copy                 1        0.00%
old-people-kicking-ass                1        0.00%
in-love-with-the-secondaries          1        0.00%
in-love-with-the-hero                 1        0.00%
best-of-my-childhood                  1        0.00%
subj_history                          1        0.00%
lit_british-english                   1        0.00%
polly-dunbar                          1        0.00%
f-science-infused-fiction             1        0.00%
f-juvenile-fiction-and-ya             1        0.00%
setting-us-wyoming                    1        0.00%
ar-level-2-5                          1        0.00%
chases-school-library-picks           1        0.00%
all-comics                            1        0.00%
poetry-nsad                           1        0.00%
favorites-at-psu                      1        0.00%
chas-addams                           1        0.00%
addams                                1        0.00%
current-property                      1        0.00%
satisfaction-good-ending              1        0.00%
genre-ya-contemporary                 1        0.00%
emotions-weird                        1        0.00%
great-romace                          1        0.00%
rebecca-caudill-2000                  1        0.00%
betsy-franco                          1        0.00%
house-that-jack-built-esq             1        0.00%
food-chains-ecology                   1        0.00%
fish-and-waterways                    1        0.00%
pond-circle                           1        0.00%
chicken-rooster                       1        0.00%
quiero-leer-ilustrados                1        0.00%
comics-mangas-graphic-novels          1        0.00%
nerdanel_gr_reto_2016_miss_scarlett        1        0.00%
recomendables                         1        0.00%
a-noter                               1        0.00%
out-of-curiousity                     1        0.00%
goreyish-shit-i-love                  1        0.00%
roal-dahl-s                           1        0.00%
stupid-book-made-me-cry               1        0.00%
medical-condition                     1        0.00%
juvenile-arthritis                    1        0.00%
granny-mac-lane                       1        0.00%
stands-alone                          1        0.00%
avika-1000                            1        0.00%
in-de-kast-nog-te-her-lezen           1        0.00%
chapter-book-favorites                1        0.00%
stoytelling                           1        0.00%
dominican-americans                   1        0.00%
carribean-heritage                    1        0.00%
one-man-band                          1        0.00%
children-s-books-early-readers        1        0.00%
children-s-books-characters           1        0.00%
kns-books                             1        0.00%
carswell-grades-k-5                   1        0.00%
dated-no                              1        0.00%
allie-lu                              1        0.00%
goose-to-read-books                   1        0.00%
hey-look-i-found-a-new-world          1        0.00%
jacob-and-me                          1        0.00%
english-9th                           1        0.00%
sloan                                 1        0.00%
gwenie                                1        0.00%
steiner-education                     1        0.00%
juvy-holiday                          1        0.00%
funny_firsts                          1        0.00%
classic-favorite                      1        0.00%
sw-orange-shelf                       1        0.00%
1122                                  1        0.00%
arham                                 1        0.00%
my-favories                           1        0.00%
written-under-pseudonym               1        0.00%
series-sagas-etc                      1        0.00%
goosebumps-presents                   1        0.00%
favorites-when-i-was-a-little-kid        1        0.00%
fiction-read-during-6th-grade         1        0.00%
for-kyle                              1        0.00%
the-secret-dinosaur-the-dinotek-adv        1        0.00%
2013-screen-free-week                 1        0.00%
vaguely-historical-fiction            1        0.00%
aty-challenge-2016                    1        0.00%
ellis-digital-bookshelf               1        0.00%
children-native-americans             1        0.00%
اسطوره                                1        0.00%
oncology                              1        0.00%
mentor-text-memoir                    1        0.00%
westchester-libraries                 1        0.00%
dec-2016                              1        0.00%
shared-with-james                     1        0.00%
3-5-year-list                         1        0.00%
yr_170330-180318-r                    1        0.00%
check-out-later                       1        0.00%
jungle-books                          1        0.00%
books-for-daisy                       1        0.00%
just-won                              1        0.00%
give-away-winner                      1        0.00%
ww2-books-to-read                     1        0.00%
homeschool-family                     1        0.00%
another-chance                        1        0.00%
20th-century-today                    1        0.00%
hidden-words                          1        0.00%
child-actors                          1        0.00%
potential-read                        1        0.00%
work-related-reading                  1        0.00%
thesis-work                           1        0.00%
started-reading-want-still            1        0.00%
add-research                          1        0.00%
books-for-kids-teens                  1        0.00%
la-quinta-finds                       1        0.00%
rfftrfr                               1        0.00%
schl-5200-literature-database         1        0.00%
title                                 1        0.00%
the-journey-stories-of-migraon        1        0.00%
written-by-kid                        1        0.00%
read-aloud-with-the-girls             1        0.00%
secrets-by-rosie-banks                1        0.00%
random_acts_of_kindness               1        0.00%
positive_adults                       1        0.00%
developmental_assets                  1        0.00%
homelessness-poverty                  1        0.00%
backstage                             1        0.00%
read-at-unknown-date                  1        0.00%
childrens-books-my-childhood-or-my        1        0.00%
lts-reading-list                      1        0.00%
suggested-books-for-2014              1        0.00%
i-read-it-in-school                   1        0.00%
ctg-fantasy                           1        0.00%
for-daniella                          1        0.00%
children-s-illustrated-canadian        1        0.00%
intersting-language                   1        0.00%
books-i-dare-recommend                1        0.00%
elyn                                  1        0.00%
pic-book-transportation               1        0.00%
to-read-to-harley                     1        0.00%
youngadultreads                       1        0.00%
adapted-mythology                     1        0.00%
meaning-of-love                       1        0.00%
diversity-biracial-latino             1        0.00%
tag-spanish                           1        0.00%
hospice-palliative-care               1        0.00%
avil-at-lib-hartselle                 1        0.00%
lauren-bb-crystal-bowman              1        0.00%
food-books-temp                       1        0.00%
library-for-school                    1        0.00%
physics-and-science                   1        0.00%
past-books-read                       1        0.00%
for-nora----to-check-out              1        0.00%
mayas-reading-list-2014               1        0.00%
hippie-granola                        1        0.00%
children-s-or-for-the-young-at-hear        1        0.00%
hippie-boho-free-spirit               1        0.00%
war-wartime                           1        0.00%
children-s-suggestions-for-nephew        1        0.00%
hogwarts-challenge                    1        0.00%
displaycase-bks                       1        0.00%
zaccheus                              1        0.00%
obey                                  1        0.00%
bartimaeus                            1        0.00%
add-to-the-bookstore                  1        0.00%
need-on-my-bookshelf                  1        0.00%
others-parenting-spiritual-formatio        1        0.00%
french-titles                         1        0.00%
pluck                                 1        0.00%
elise-broachgreat-lakes-great-books        1        0.00%
dystopian-sci-fi-weird                1        0.00%
reading-responses                     1        0.00%
summer-holiday-homework               1        0.00%
skool-stuffles                        1        0.00%
seriously-need-to-read                1        0.00%
bootleg                               1        0.00%
need-it-like-air                      1        0.00%
beloved-teenager-s                    1        0.00%
tbr-wl-4                              1        0.00%
five-stars-but-missing-something        1        0.00%
picked-up-out-of-boredom              1        0.00%
secondary-bob                         1        0.00%
english_9                             1        0.00%
x-2013                                1        0.00%
freebee                               1        0.00%
christmas-read-aloud                  1        0.00%
goodreads-recommended                 1        0.00%
ya-mg-fiction                         1        0.00%
young-reader-african-american-chara        1        0.00%
illustration-research                 1        0.00%
var                                   1        0.00%
2012-for-me                           1        0.00%
non-firction                          1        0.00%
patterns-form-iterations              1        0.00%
2012-2x2-submissions                  1        0.00%
srp-2015-younger                      1        0.00%
child-adult-misunderstandings         1        0.00%
picture-books-398                     1        0.00%
fcg                                   1        0.00%
oh-tannenbaum                         1        0.00%
wild-woman-wear-red                   1        0.00%
booksforgrown-ups                     1        0.00%
1-review-needed                       1        0.00%
physical-education                    1        0.00%
for-super-e                           1        0.00%
biomimicry                            1        0.00%
books-that-destroy-your-ego           1        0.00%
on-actual-bookshelf                   1        0.00%
read-prior-to-2014                    1        0.00%
scanned-to-sort                       1        0.00%
kids-cds                              1        0.00%
kidstuffs                             1        0.00%
humantities-7-40-books-challenge        1        0.00%
best-novels                           1        0.00%
books-i-really-dnt-lik                1        0.00%
books-read-with-vincent               1        0.00%
december-march                        1        0.00%
2012-2013-short-list-older            1        0.00%
ms_g6                                 1        0.00%
ms_bookcorner                         1        0.00%
normal-life                           1        0.00%
sakura-medal-2013-read                1        0.00%
cormacs-reviews                       1        0.00%
2013-shortlist-older                  1        0.00%
book-jar-autores-r                    1        0.00%
profileshelf                          1        0.00%
lidos-infancia                        1        0.00%
1960-2000                             1        0.00%
brasil-lit-atual                      1        0.00%
read-standalones                      1        0.00%
marcelo-martelo-marmelo               1        0.00%
quando-era-criança                    1        0.00%
look-inside                           1        0.00%
lah-read-alone                        1        0.00%
axis                                  1        0.00%
100-in-2016                           1        0.00%
dealing-with-trouble                  1        0.00%
zc-challenge-13                       1        0.00%
italy-modern                          1        0.00%
twenty-eleven                         1        0.00%
really-want-to-read-asap              1        0.00%
living-room-big-bottom                1        0.00%
no-catalogue                          1        0.00%
packing-inv-6                         1        0.00%
мистър-фини                           1        0.00%
cacti                                 1        0.00%
albi-illustrati-s-u                   1        0.00%
coloring-art                          1        0.00%
most-anticipated-release              1        0.00%
2019-ls-potential                     1        0.00%
2018-s-book                           1        0.00%
upper-elem-ya                         1        0.00%
lgbtqi-fiction                        1        0.00%
tbreleased                            1        0.00%
2018-debuts                           1        0.00%
mar-apr-may-17                        1        0.00%
books-to-read-with-ciaran             1        0.00%
needs-amazon-review                   1        0.00%
melina-marchetta                      1        0.00%

In [ ]:
# --- Extract Top Shelf Tags ---
import ast
import re

# Obvious exclusions: administrative / status / ownership / platform shelves
OBVIOUS_SHELF_EXCLUSIONS = {
    # Reading status / workflow
    "to-read", "currently-reading", "read", "finished", "unread",
    "did-not-finish", "didn-t-finish", "abandoned", "not-read",
    "already-read", "reread", "re-read", "to-re-read", "to-reread",

    # Ownership / library / collection
    "owned", "books-i-own", "owned-books", "i-own", "own-it", "we-own",
    "books-we-own", "books-i-have", "my-books", "my-bookshelf", "bookshelf",
    "my-library", "library", "library-book", "library-books", "school-library",
    "public-library", "personal-library", "home-library", "our-library",
    "in-library", "from-library", "borrowed", "borrowed-from-library",
    "library-available", "on-my-shelf", "on-my-bookshelf",
    "in-the-collection", "collection", "inventory",

    # Purchase / acquisition
    "to-buy", "want-to-buy", "need-to-buy", "to-get", "buy", "bought",
    "want-to-own", "own-to-read", "owned-to-read",

    # Generic admin / vague
    "default", "books", "book", "shelved", "other", "general", "have",
    "mine", "new", "all-books",

    # Ratings / review tracking
    "review", "reviewed", "reviews", "for-review", "to-review",
    "5-stars", "4-stars", "3-stars", "2-stars", "5-star", "4-star", "3-star",

    # Platform / format / source
    "kindle", "ebook", "ebooks", "e-book", "e-books", "audio", "audiobook",
    "audiobooks", "audio-book", "audio-books", "audible", "digital",
    "on-kindle", "kindle-books",

    # User-relationship / sentiment shelves
    "favorites", "favorite", "favourites", "favourite", "my-favorites",
    "all-time-favorites", "all-time-favourites", "favorite-books",
    "favourite-books", "childhood", "nostalgia", "my-childhood",
    "read-as-a-kid", "read-as-a-child", "from-my-childhood",
    "childhood-favorites", "childhood-favourites", "childhood-faves",
    "childhood-memories", "books-from-my-childhood", "books-from-childhood",
    "when-i-was-young", "when-i-was-a-kid",

    # Numeric / junk labels
    "1", "2", "3", "a", "e", "x", "pb", "sub",
}

YEAR_SHELF_PATTERNS = [
    r"^read[-_ ]?in[-_ ]?\d{4}$",
    r"^read[-_ ]?\d{4}$",
    r"^\d{4}[-_ ]?reads$",
    r"^\d{4}[-_ ]?books$",
    r"^\d{4}[-_ ]?read$",
]

def is_excluded_shelf(name: str) -> bool:
    """Return True if the cleaned shelf name should be excluded."""
    if name in OBVIOUS_SHELF_EXCLUSIONS:
        return True
    for pattern in YEAR_SHELF_PATTERNS:
        if re.fullmatch(pattern, name):
            return True
    return False

def extract_top_shelf_tags(shelves_entry, top_n=5):
    """Extract top N informative shelf names after excluding obvious non-content shelves."""
    shelves = parse_shelves_entry(shelves_entry)
    shelf_list = []

    for d in shelves:
        if not isinstance(d, dict):
            continue

        name = d.get("name")
        count = d.get("count")

        if name is None:
            continue

        name_clean = str(name).strip().lower()
        if not name_clean or is_excluded_shelf(name_clean):
            continue

        try:
            count_num = int(count)
        except Exception:
            count_num = 0

        shelf_list.append((name_clean, count_num))

    # Sort by count descending, then alphabetically
    shelf_list.sort(key=lambda x: (-x[1], x[0]))

    # Deduplicate names while preserving order
    seen = set()
    top_names = []
    for name, _ in shelf_list:
        if name not in seen:
            seen.add(name)
            top_names.append(name)
        if len(top_names) == top_n:
            break

    return top_names

# 1. Create top_shelf_tags on books_df_cleaned
books_df_cleaned["top_shelf_tags"] = books_df_cleaned["popular_shelves"].apply(extract_top_shelf_tags)

# 2. Merge top_shelf_tags into baseline_df (not events_df)
if "top_shelf_tags" in baseline_df.columns:
    baseline_df = baseline_df.drop(columns=["top_shelf_tags"])

baseline_df = baseline_df.merge(
    books_df_cleaned[["book_id", "top_shelf_tags"]],
    on="book_id",
    how="left"
)

# 3. Print stats and sample from books_df_cleaned
num_nonempty = books_df_cleaned["top_shelf_tags"].apply(lambda x: bool(x)).sum()
total = len(books_df_cleaned)
print(f"Rows with non-empty top_shelf_tags in books_df_cleaned: {num_nonempty} ({num_nonempty / total:.2%})")

sample_cols = ["book_id", "title", "popular_shelves", "top_shelf_tags"]
sample = books_df_cleaned[sample_cols].head(10)
print("\nSample of top_shelf_tags from books_df_cleaned:")
print(sample.to_string(index=False))

# 4. Verify merge into baseline_df
num_baseline_nonempty = baseline_df["top_shelf_tags"].apply(lambda x: isinstance(x, list) and len(x) > 0).sum()
total_baseline = len(baseline_df)
print(f"\nRows with non-empty top_shelf_tags in baseline_df: {num_baseline_nonempty} ({num_baseline_nonempty / total_baseline:.2%})")

baseline_sample_cols = ["user_id", "book_id", "event_time", "top_shelf_tags"]
baseline_sample_cols = [c for c in baseline_sample_cols if c in baseline_df.columns]

print("\nSample of merged top_shelf_tags in baseline_df:")
print(baseline_df[baseline_sample_cols].head(10).to_string(index=False))

# 5. Print most common retained shelf tags after exclusion
from collections import Counter

all_retained_shelves = [
    shelf
    for shelf_list in books_df_cleaned["top_shelf_tags"]
    if isinstance(shelf_list, list)
    for shelf in shelf_list
]

shelf_counter = Counter(all_retained_shelves)

print("\nTop retained shelf tags after removing obvious non-content shelves:")
for shelf, count in shelf_counter.most_common(30):
    print(f"{shelf}: {count}")

Rows with non-empty top_shelf_tags in books_df_cleaned: 124037 (100.00%)

Sample of top_shelf_tags from books_df_cleaned:
 book_id                                                                         title                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  popular_shelves                                                                                     top_shelf_tags
  287141                                                 The Aeneid for Boys and Girls                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              [{'count': '56', 'name': 'to-read'}, {'count': '10', 'name': 'currently-reading'}, {'count': '4', 'name': 'history'}, {'count': '3', 'name': 'classics'}, {'count': '2', 'name': 'level-4to5'}, {'count': '2', 'name': 'school-books'}, {'count': '2', 'name': 'yesterday'}, {'count': '2', 'name': 'school'}, {'count': '2', 'name': 'classic'}, {'count': '2', 'name': 'read-alouds'}, {'count': '1', 'name': 'children-s-literature'}, {'count': '1', 'name': 'classic-ed'}, {'count': '1', 'name': 'waldorf-homeschool'}, {'count': '1', 'name': '6th-grade'}, {'count': '1', 'name': 'myths-folktales-fairytales'}, {'count': '1', 'name': 'abandoned'}, {'count': '1', 'name': 'tapestry-of-grace-year-1-dialectic'}, {'count': '1', 'name': 'default'}, {'count': '1', 'name': 'myth'}, {'count': '1', 'name': 'fantasy'}, {'count': '1', 'name': '14'}, {'count': '1', 'name': 'school-room'}, {'count': '1', 'name': 'history-intermediate'}, {'count': '1', 'name': 'rome'}, {'count': '1', 'name': 'literature'}, {'count': '1', 'name': 'classical-world'}, {'count': '1', 'name': 'childrens-literature'}, {'count': '1', 'name': 'willem-s'}, {'count': '1', 'name': 'children-s-fiction'}, {'count': '1', 'name': 'elem-middle'}, {'count': '1', 'name': 'digital'}, {'count': '1', 'name': 'youth-lit'}, {'count': '1', 'name': 'teaching-english'}, {'count': '1', 'name': 'english'}, {'count': '1', 'name': 'my-babies'}, {'count': '1', 'name': 'from-cynthia'}, {'count': '1', 'name': 'ya-children'}, {'count': '1', 'name': 'scanned-own'}, {'count': '1', 'name': '13-virgil'}, {'count': '1', 'name': 'ancient'}, {'count': '1', 'name': 'tog-year-1-dialectic'}, {'count': '1', 'name': 'ancients-5000bc-ad400'}, {'count': '1', 'name': 'historical'}, {'count': '1', 'name': 'children'}, {'count': '1', 'name': 'ancient-history'}, {'count': '1', 'name': 'military'}, {'count': '1', 'name': 'tapestry-of-grace'}, {'count': '1', 'name': 'school-2014-2015'}, {'count': '1', 'name': 'tapestry-year-1'}, {'count': '1', 'name': 'for-school'}, {'count': '1', 'name': 'children-s'}, {'count': '1', 'name': 'kids-books'}, {'count': '1', 'name': 'homeschooling'}, {'count': '1', 'name': 'own-homeschool-lit'}, {'count': '1', 'name': 'own-ebook'}, {'count': '1', 'name': 'yc-level-2'}, {'count': '1', 'name': 'tog-yr1'}, {'count': '1', 'name': '4th-grade'}, {'count': '1', 'name': 'myths-and-legends'}, {'count': '1', 'name': 'steven'}, {'count': '1', 'name': 'yesterdays-classics'}, {'count': '1', 'name': 'ebook-review-to-read'}, {'count': '1', 'name': 'ebook'}, {'count': '1', 'name': 'year2-ao'}, {'count': '1', 'name': 'legends'}, {'count': '1', 'name': 'elisha'}, {'count': '1', 'name': 'read-with-kids'}, {'count': '1', 'name': 'for-calvin'}, {'count': '1', 'name': 'humanities'}, {'count': '1', 'name': 'books-for-addy'}, {'count': '1', 'name': 'history-ancients'}, {'count': '1', 'name': 'novels'}, {'count': '1', 'name': 'greek-history'}, {'count': '1', 'name': 'school-2011-12'}, {'count': '1', 'name': 'ancient-classics'}, {'count': '1', 'name': 'jill'}, {'count': '1', 'name': 'read-in-2010'}, {'count': '1', 'name': 'curric'}]                                              [history, classics, classic, level-4to5, read-alouds]
 6066812                        All's Fairy in Love and War (Avalon: Web of Magic, #8)                                                                                                                              [{'count': '515', 'name': 'to-read'}, {'count': '25', 'name': 'fantasy'}, {'count': '11', 'name': 'owned'}, {'count': '11', 'name': 'books-i-own'}, {'count': '9', 'name': 'currently-reading'}, {'count': '9', 'name': 'favorites'}, {'count': '9', 'name': 'magic'}, {'count': '9', 'name': 'avalon'}, {'count': '8', 'name': 'young-adult'}, {'count': '6', 'name': 'series'}, {'count': '6', 'name': 'fiction'}, {'count': '5', 'name': 'books'}, {'count': '4', 'name': 'childrens-books'}, {'count': '4', 'name': 'owned-books'}, {'count': '4', 'name': 'adventure'}, {'count': '4', 'name': 'middle-grade'}, {'count': '4', 'name': 'children'}, {'count': '4', 'name': 'avalon-web-of-magic'}, {'count': '3', 'name': 'ya'}, {'count': '3', 'name': 'want'}, {'count': '3', 'name': 'teen'}, {'count': '3', 'name': 'faeries'}, {'count': '3', 'name': 'childrens'}, {'count': '2', 'name': 'children-s'}, {'count': '2', 'name': '4-stars'}, {'count': '2', 'name': 'library'}, {'count': '2', 'name': 'default'}, {'count': '2', 'name': 'dragons'}, {'count': '2', 'name': 'witches'}, {'count': '2', 'name': 'paranormal'}, {'count': '2', 'name': 'r'}, {'count': '2', 'name': 'childhood'}, {'count': '2', 'name': 'my-childhood'}, {'count': '2', 'name': 'children-s-books'}, {'count': '2', 'name': 'rachel-roberts'}, {'count': '2', 'name': 'fairies'}, {'count': '2', 'name': 'childhood-favorites'}, {'count': '2', 'name': 'kids-books'}, {'count': '2', 'name': 'kids'}, {'count': '2', 'name': 'my-books'}, {'count': '2', 'name': 'avalon--web-of-magic'}, {'count': '2', 'name': 'read-in-2009'}, {'count': '2', 'name': 'books-i-have'}, {'count': '2', 'name': 'to-buy'}, {'count': '1', 'name': 'own-own-unread'}, {'count': '1', 'name': 'own-own'}, {'count': '1', 'name': 'nostalgia'}, {'count': '1', 'name': 'kid-s-books'}, {'count': '1', 'name': 'america-and-canada'}, {'count': '1', 'name': 'low-fantasy'}, {'count': '1', 'name': '5th'}, {'count': '1', 'name': 'tbr-series'}, {'count': '1', 'name': 'part-of-a-series'}, {'count': '1', 'name': 'fantasy-ya'}, {'count': '1', 'name': 'novel'}, {'count': '1', 'name': 'where-i-started'}, {'count': '1', 'name': 'kj2016-17-2nd-3rd-grade'}, {'count': '1', 'name': 'kids-books-tracking'}, {'count': '1', 'name': 'book-library-now'}, {'count': '1', 'name': 'faerie-tales'}, {'count': '1', 'name': 'need-to-buy'}, {'count': '1', 'name': 'reread-in-2015'}, {'count': '1', 'name': 'personal-shelf'}, {'count': '1', 'name': 'childhood-favourites'}, {'count': '1', 'name': 'all-time-favourites'}, {'count': '1', 'name': 'novels'}, {'count': '1', 'name': 'to-buy-middlegrade'}, {'count': '1', 'name': 'literature'}, {'count': '1', 'name': 'bought'}, {'count': '1', 'name': 'bookshelf'}, {'count': '1', 'name': 'sci-fi-fantasy'}, {'count': '1', 'name': 'physical-copies'}, {'count': '1', 'name': 'childhood-books'}, {'count': '1', 'name': '0-books-i-own'}, {'count': '1', 'name': 'avalonwebofmagicseries'}, {'count': '1', 'name': 'shelfari-wishlist'}, {'count': '1', 'name': 'tbr-2014'}, {'count': '1', 'name': 'science-fiction-fantasy'}, {'count': '1', 'name': 'pc-100-199'}, {'count': '1', 'name': 'e-book'}, {'count': '1', 'name': 'c-purple'}, {'count': '1', 'name': 'author-r'}, {'count': '1', 'name': 'action-adventure'}, {'count': '1', 'name': 'a'}, {'count': '1', 'name': 'reg'}, {'count': '1', 'name': 'books-that-i-own'}, {'count': '1', 'name': 'middle-grade-lit'}, {'count': '1', 'name': 'child'}, {'count': '1', 'name': 'younger-reads'}, {'count': '1', 'name': 'fantasy-dystopians'}, {'count': '1', 'name': 'currently-have'}, {'count': '1', 'name': 'no-longer-have'}, {'count': '1', 'name': 'elements'}, {'count': '1', 'name': 'own-it'}, {'count': '1', 'name': 'currently-in-bookshelf'}, {'count': '1', 'name': 'my-favorites'}, {'count': '1', 'name': 'to-re-read'}, {'count': '1', 'name': 'not-available-on-kindle'}, {'count': '1', 'name': 'have-read'}, {'count': '1', 'name': 'childrens-and-middle-grade'}]                                                     [fantasy, avalon, magic, young-adult, fiction]
   89378                                                                    Dog Heaven                 [{'count': '450', 'name': 'to-read'}, {'count': '64', 'name': 'picture-books'}, {'count': '26', 'name': 'animals'}, {'count': '22', 'name': 'children-s-books'}, {'count': '21', 'name': 'childrens'}, {'count': '20', 'name': 'dogs'}, {'count': '18', 'name': 'death'}, {'count': '17', 'name': 'children'}, {'count': '16', 'name': 'picture-book'}, {'count': '12', 'name': 'children-s'}, {'count': '12', 'name': 'favorites'}, {'count': '10', 'name': 'kids'}, {'count': '8', 'name': 'currently-reading'}, {'count': '8', 'name': 'pets'}, {'count': '8', 'name': 'children-s-lit'}, {'count': '8', 'name': 'fiction'}, {'count': '8', 'name': 'childrens-books'}, {'count': '7', 'name': 'heaven'}, {'count': '7', 'name': 'dog-books'}, {'count': '6', 'name': 'children-s-literature'}, {'count': '5', 'name': 'cynthia-rylant'}, {'count': '5', 'name': 'grief'}, {'count': '4', 'name': 'default'}, {'count': '4', 'name': 'library'}, {'count': '3', 'name': 'kids-books'}, {'count': '3', 'name': 'bibliotherapy'}, {'count': '3', 'name': 'religion'}, {'count': '3', 'name': 'diversity-inclusion'}, {'count': '3', 'name': 'childrens-lit'}, {'count': '3', 'name': 'books-i-own'}, {'count': '2', 'name': 'death-grief'}, {'count': '2', 'name': 'picture-story-books'}, {'count': '2', 'name': 'children-s-picture'}, {'count': '2', 'name': 'kiddos'}, {'count': '2', 'name': 'spirituality'}, {'count': '2', 'name': 'loss-of-a-pet'}, {'count': '2', 'name': 'childhood'}, {'count': '2', 'name': 'school-counseling'}, {'count': '2', 'name': 'classroom-library'}, {'count': '2', 'name': 'self-help'}, {'count': '2', 'name': 'young-children'}, {'count': '2', 'name': 'unfortunate-events'}, {'count': '2', 'name': 'helpful'}, {'count': '2', 'name': 'appreciation'}, {'count': '2', 'name': 'acceptance'}, {'count': '2', 'name': 'ece-3601'}, {'count': '2', 'name': 'class-library'}, {'count': '2', 'name': 'closet'}, {'count': '2', 'name': '813-5'}, {'count': '2', 'name': 'classroom'}, {'count': '2', 'name': 'dog-tales'}, {'count': '2', 'name': 'christian'}, {'count': '2', 'name': 'angels'}, {'count': '2', 'name': 'non-fiction'}, {'count': '2', 'name': 'illustrated'}, {'count': '2', 'name': 'children-s-book'}, {'count': '2', 'name': 'god'}, {'count': '2', 'name': 'animal-books'}, {'count': '2', 'name': 'picture'}, {'count': '2', 'name': 'kid-books'}, {'count': '2', 'name': 'children-s-picture-books'}, {'count': '2', 'name': 'childrens-favorites'}, {'count': '1', 'name': 'year-2017'}, {'count': '1', 'name': 'l'}, {'count': '1', 'name': 'at-library'}, {'count': '1', 'name': 'to-read-fiction'}, {'count': '1', 'name': 'h-h-s'}, {'count': '1', 'name': 'a2'}, {'count': '1', 'name': 'a'}, {'count': '1', 'name': 'kids-and-teen'}, {'count': '1', 'name': 'zone-2'}, {'count': '1', 'name': 'teach-writing'}, {'count': '1', 'name': 'read-fiction-child'}, {'count': '1', 'name': 'premiere-wishlist'}, {'count': '1', 'name': 'picturebooks'}, {'count': '1', 'name': 'my-library-own'}, {'count': '1', 'name': 'mg-ya-picture-books-fiction'}, {'count': '1', 'name': 'mental-health-resources-for-kids'}, {'count': '1', 'name': 'littles'}, {'count': '1', 'name': 'kids-fiction'}, {'count': '1', 'name': 'kids-family'}, {'count': '1', 'name': 'elem-early'}, {'count': '1', 'name': 'dogs-animals'}, {'count': '1', 'name': 'death-dying-grief'}, {'count': '1', 'name': 'childrens_picture-books'}, {'count': '1', 'name': 'childrens-fiction'}, {'count': '1', 'name': 'books-about-scary-stuff'}, {'count': '1', 'name': 'best-secular-judaica-resources'}, {'count': '1', 'name': 'author-study-cynthia-rylant'}, {'count': '1', 'name': 'animals-picture-book'}, {'count': '1', 'name': 'animal-tales'}, {'count': '1', 'name': 'alex-s-books-at-5-6'}, {'count': '1', 'name': 'age-slastic_50_1gr'}, {'count': '1', 'name': 'afterlife-literature'}, {'count': '1', 'name': '1000bb4k'}, {'count': '1', 'name': 'kids-read'}, {'count': '1', 'name': 'kids-recommend-gr1-2-c-t-l'}, {'count': '1', 'name': 'mortality'}, {'count': '1', 'name': 'izzy-s-summer-1-000'}, {'count': '1', 'name': 'k-2'}]                                        [picture-books, animals, children-s-books, childrens, dogs]

Item-Side Semantic Embedding
- item_text_for_embedding (creating combined text string of title + meaningful description + top shelf tags)
- item_semantic_embedding_static
    - using SBERT (Sentence-BERT)

In [ ]:
# --- Create item_text_for_embedding ---

def build_item_text_for_embedding(row):
    parts = []

    # Title
    title = row.get("title", None)
    if pd.notna(title):
        title_str = str(title).strip()
        if title_str:
            parts.append(title_str)

    # Description: include only if meaningful, and use truncated version
    if int(row.get("has_meaningful_description", 0)) == 1:
        description = row.get("description_truncated", None)
        if pd.notna(description):
            description_str = str(description).strip()
            if description_str:
                parts.append(description_str)

    # Top shelf tags
    tags = row.get("top_shelf_tags", [])
    if isinstance(tags, list):
        tags_clean = [str(tag).strip() for tag in tags if pd.notna(tag) and str(tag).strip()]
        if tags_clean:
            parts.append(" ".join(tags_clean))

    # Always return a string
    return " [SEP] ".join(parts) if parts else ""

books_df_cleaned["item_text_for_embedding"] = books_df_cleaned.apply(
    build_item_text_for_embedding,
    axis=1
)

# --- Summary ---
nonempty_mask = books_df_cleaned["item_text_for_embedding"].str.strip() != ""
num_nonempty = int(nonempty_mask.sum())
total = len(books_df_cleaned)
avg_len = books_df_cleaned.loc[nonempty_mask, "item_text_for_embedding"].str.len().mean()

print(f"Rows with non-empty item_text_for_embedding: {num_nonempty} ({num_nonempty / total:.2%})")
print(
    f"Average character length (non-empty only): {avg_len:.2f}"
    if num_nonempty > 0 else
    "Average character length (non-empty only): N/A"
)

sample_cols = [
    "book_id",
    "title",
    "has_meaningful_description",
    "description_truncated",
    "top_shelf_tags",
    "item_text_for_embedding",
]
sample_cols = [c for c in sample_cols if c in books_df_cleaned.columns]

print("\nSample of item_text_for_embedding:")
print(books_df_cleaned[sample_cols].head(10).to_string(index=False))

Rows with non-empty item_text_for_embedding: 124037 (100.00%)
Average character length (non-empty only): 550.19

Sample of item_text_for_embedding:
 book_id                                                                         title  has_meaningful_description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        description_truncated                                                                                     top_shelf_tags                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  item_text_for_embedding
  287141                                                 The Aeneid for Boys and Girls                           1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Relates in vigorous prose the tale of Aeneas, the legendary ancestor of Romulus, who escaped from the burning city of Troy and wandered the Mediterranean for years before settling in Italy. Patterned after the Iliad and the Odyssey, the Aeneid was composed as an epic poem by Virgil, to glorify the imperial city of Rome.                                              [history, classics, classic, level-4to5, read-alouds]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              The Aeneid for Boys and Girls [SEP] Relates in vigorous prose the tale of Aeneas, the legendary ancestor of Romulus, who escaped from the burning city of Troy and wandered the Mediterranean for years before settling in Italy. Patterned after the Iliad and the Odyssey, the Aeneid was composed as an epic poem by Virgil, to glorify the imperial city of Rome. [SEP] history classics classic level-4to5 read-alouds
 6066812                        All's Fairy in Love and War (Avalon: Web of Magic, #8)                           1 To Kara's astonishment, she discovers that a portal has opened in her bedroom closet and two goblins have fallen through! They refuse to return to the fairy realms and be drafted for an impending war. In an attempt to roust the pesky creatures, Kara falls through the portal, smack into the middle of a huge war. Kara meets Queen Selinda, who appoints Kara as a Fairy Princess and assigns her an impossible task: to put an end to the war using her diplomatic skills. All's Fairy In Love And War is the eighth book in Avalon: Web of Magic, a twelve-book fantasy series for middle grade readers. Through their magical journey, the teenage heroines discover who they really are . . . and run into plenty of good guys, bad guys, and cute guys. Out of print for two years, Seven Seas is pleased to return the Avalon series to print in editions targeted for today's readers, with new manga-style covers and interior illustrations.                                                     [fantasy, avalon, magic, young-adult, fiction] All's Fairy in Love and War (Avalon: Web of Magic, #8) [SEP] To Kara's astonishment, she discovers that a portal has opened in her bedroom closet and two goblins have fallen through! They refuse to return to the fairy realms and be drafted for an impending war. In an attempt to roust the pesky creatures, Kara falls through the portal, smack into the middle of a huge war. Kara meets Queen Selinda, who appoints Kara as a Fairy Princess and assigns her an impossible task: to put an end to the war using her diplomatic skills. All's Fairy In Love And War is the eighth book in Avalon: Web of Magic, a twelve-book fantasy series for middle grade readers. Through their magical journey, the teenage heroines discover who they really are . . . and run into plenty of good guys, bad guys, and cute guys. Out of print for two years, Seven Seas is pleased to return the Avalon series to print in editions targeted for today's readers, with new manga-style covers and interior illustrations. [SEP] fantasy avalon magic young-adult fiction
   89378                                                                    Dog Heaven                           1                                                                                                                                                                                                                                                                             In Newbery Medalist Cynthia Rylant's classic bestseller, the author comforts readers young and old who have lost a dog. Recommended highly by pet lovers around the world, Dog Heaven not only comforts but also brings a tear to anyone who is devoted to a pet. From expansive fields where dogs can run and run to delicious biscuits no dog can resist, Rylant paints a warm and affectionate picture of the ideal place God would, of course, create for man's best friend. The first picture book illustrated by the author, Dog Heaven is enhanced by Rylant's bright, bold paintings that perfectly capture an afterlife sure to bring solace to anyone who is grieving.                                        [picture-books, animals, children-s-books, childrens, dogs]                                                                                                                                                                                                                                                                                                            Dog Heaven [SEP] In Newbery Medalist Cynthia Rylant's classic bestseller, the author comforts readers young and old who have lost a dog. Recommended highly by pet lovers around the world, Dog Heaven not only comforts but also brings a tear to anyone who is devoted to a pet. From expansive fields where dogs can run and run to delicious biscuits no dog can resist, Rylant paints a warm and affectionate picture of the ideal place God would, of course, create for man's best friend. The first picture book illustrated by the author, Dog Heaven is enhanced by Rylant's bright, bold paintings that perfectly capture an afterlife sure to bring solace to anyone who is grieving. [SEP] picture-books animals children-s-books childrens dogs
 3209312 Moths and Mothers, Feathers and Fathers: A Story About a Tiny Owl Named Squib                           0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          NaN [bedtime-with-amir, books-to-buy-look-into, children, children-s-picture-books, illustrated-books]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Moths and Mothers, Feathers and Fathers: A Story About a Tiny Owl Named Squib [SEP] bedtime-with-amir books-to-buy-look-into children children-s-picture-books illustrated-books
 1698376                                                               What Do You Do?                           1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               WHAT DO YOU DO? A hen lays eggs... A cow gives milk... An elephant squirts water... But what does a beetle do?                                        [animals, board-books, board-book, picture-books, children]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         What Do You Do? [SEP] WHAT DO YOU DO? A hen lays eggs... A cow gives milk... An elephant squirts water... But what does a beetle do? [SEP] animals board-books board-book picture-books children
 2592648                                        It's Funny Where Ben's Train Takes Him                           1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Ben draws a train that takes him to all sorts of wonderful places before returning him to his own bed.                           [childrens, picture-book, picture-books, aj-books, books-read-to-calvin]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             It's Funny Where Ben's Train Takes Him [SEP] Ben draws a train that takes him to all sorts of wonderful places before returning him to his own bed. [SEP] childrens picture-book picture-books aj-books books-read-to-calvin
32615012                                                The tale of Jemima puddle-duck                           1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Searching for a convenient nesting place, befuddled Jemima Puddle-Duck chooses a fox's den and is then rescued by barnyard collie and pups from the fox's cooking pot.                                       [childrens, children, children-s-books, children-s, fiction]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 The tale of Jemima puddle-duck [SEP] Searching for a convenient nesting place, befuddled Jemima Puddle-Duck chooses a fox's den and is then rescued by barnyard collie and pups from the fox's cooking pot. [SEP] childrens children children-s-books children-s fiction
 3631900                                           Amadi's Snowman: A Story of Reading                           1                                                                                                                                                                                                                                                                                                                                                                                                                    When Amadi disobeys his mother and runs off to the market instead of sticking around for a reading lesson, he encounters a much-admired older boy secretly reading at a book stall. Crowding himself in among the stacks of books, Amadi becomes intrigued by a storybook with pictures of a strange white creature with a carrot for a nose. Over the course of a typical mischievous day, unable to shake his questions about the snowman, Amadi discovers the vast world reading could open up--especially for an Igbo man of Nigeria.                            [picture-books, picture-book, fiction, multicultural, children-s-books]                                                                                                                                                                                                                                                                                                                                                                                                              Amadi's Snowman: A Story of Reading [SEP] When Amadi disobeys his mother and runs off to the market instead of sticking around for a reading lesson, he encounters a much-admired older boy secretly reading at a book stall. Crowding himself in among the stacks of books, Amadi becomes intrigued by a storybook with pictures of a strange white creature with a carrot for a nose. Over the course of a typical mischievous day, unable to shake his questions about the snowman, Amadi discovers the vast world reading could open up--especially for an Igbo man of Nigeria. [SEP] picture-books picture-book fiction multicultural children-s-books

In [ ]:
# --- Merge item_text_for_embedding into baseline_df and verify the merge ---

# Drop existing column first to avoid duplicate-column issues on re-run
if "item_text_for_embedding" in baseline_df.columns:
    baseline_df = baseline_df.drop(columns=["item_text_for_embedding"])

# Merge from books_df_cleaned by book_id
baseline_df = baseline_df.merge(
    books_df_cleaned[["book_id", "item_text_for_embedding"]],
    on="book_id",
    how="left",
    validate="many_to_one"
)

# --- Verification ---
num_nonempty = baseline_df["item_text_for_embedding"].fillna("").str.strip().ne("").sum()
total = len(baseline_df)

print(f"Rows with non-empty item_text_for_embedding in baseline_df: {num_nonempty} ({num_nonempty / total:.2%})")

verify_cols = ["user_id", "book_id", "event_time", "item_text_for_embedding"]
verify_cols = [c for c in verify_cols if c in baseline_df.columns]

print("\nSample of merged item_text_for_embedding in baseline_df:")
print(baseline_df[verify_cols].head(10).to_string(index=False))

Rows with non-empty item_text_for_embedding in baseline_df: 8770364 (100.00%)

Sample of merged item_text_for_embedding in baseline_df:
                         user_id  book_id                event_time                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 item_text_for_embedding
dcdc48c7d14a6467cf277c9c0919eb02     6310 1990-01-01 08:00:00+00:00                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Charlie and the Chocolate Factory (Charlie Bucket, #1) [SEP] Complete with stunning new movie art for the cover, and an eight-page full-color insert of stills from director Tim Burton's new adaptation, Dahl's treasured novel appears unabridged in this tie-in edition. [SEP] childrens fantasy fiction classics children
dcdc48c7d14a6467cf277c9c0919eb02     6319 1990-01-01 08:00:00+00:00                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              The BFG [SEP] Captured by a giant! The BFG is no ordinary bone-crunching giant. He is far too nice and jumbly. It's lucky for Sophie that he is. Had she been carried off in the middle of the night by the Bloodbottler, the Fleshlumpeater, the Bonecruncher, or any of the other giants-rather than the BFG-she would have soon become breakfast. When Sophie hears that they are flush-bunking off in England to swollomp a few nice little chiddlers, she decides she must stop them once and for all. And the BFG is going to help her! [SEP] childrens fantasy children-s children-s-books classics
dcdc48c7d14a6467cf277c9c0919eb02     6689 1990-01-01 08:00:00+00:00                                                                                                                                                                                                                                                                                                                                                                                                                        James and the Giant Peach [SEP] When James accidentally drops some magic crystals by the old peach tree, strange things start to happen. The peach at the top of the tree begins to grow, and before long it's as big as a house. When James discovers a secret entranceway into the fruit and crawls inside, he meets wonderful new friends--the Old-Green-Grasshopper, the dainty Ladybug, and the Centipede of the multiple boots. After years of feeling like an outsider in his aunts' house, James finally found a place where he belongs. With a snip of the stem, the peach household starts rolling away--and the adventure begins! Roald Dahl's first and most widely celebrated book for young people continues to thrill readers around the world. "This is a stunning book to be cherished for its story, a superb fantasy."--Chicago Tribune "A beautifully written, fantastic book."--Christian Science Monitor [SEP] childrens fantasy fiction children classics
dcdc48c7d14a6467cf277c9c0919eb02    10365 1990-01-01 08:00:00+00:00                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Where the Red Fern Grows [SEP] A loving threesome, they ranged the dark hills and river bottoms of Cherokee country. Old Dan had the brawn. Little Ann had the brains, and Billy had the will to make them into the finest hunting team in the valley. Glory and victory were coming to them, but sadness waited too. Where the Red Fern Grows is an exciting tale of love and adventure you'll never forget. [SEP] classics fiction young-adult childrens children
dcdc48c7d14a6467cf277c9c0919eb02    39988 1990-01-01 08:00:00+00:00 Matilda [SEP] Matilda is a little girl who is far too good to be true. At age five-and-a-half she's knocking off double-digit multiplication problems and blitz-reading Dickens. Even more remarkably, her classmates love her even though she's a super-nerd and the teacher's pet. But everything is not perfect in Matilda's world. For starters she has two of the most idiotic, self-centered parents who ever lived. Then there's the large, busty nightmare of a school principal, Mrs. ("The") Trunchbull, a former hammer-throwing champion who flings children at will and is approximately as sympathetic as a bulldozer. Fortunately for Matilda, she has the inner resources to deal with such annoyances: astonishing intelligence, saintly patience, and an innate predilection for revenge. She warms up with some practical jokes aimed at her hapless parents, but the true test comes when she rallies in defense of her teacher, the sweet Miss Honey, against the diabolical Trunchbull. There is never any doubt that Matilda will carry the day. Even so, this wonderful story is far from predictable. Roald Dahl, while keeping the plot moving imaginatively, also has an unerring ear for emotional truth. The reader cares about Matilda because in addition to all her other gifts, she has real feelings. [SEP] young-adult childrens-books ya kids-books childhood-books
dcdc48c7d14a6467cf277c9c0919eb02   385247 1990-01-01 08:00:00+00:00                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Charlie and the Great Glass Elevator [SEP] Now that he's won the chocolate factory, what's next for Charlie? Last seen flying through the sky in a giant elevator in Charlie and the Chocolate Factory, Charlie Bucket's back for another adventure. When the giant elevator picks up speed, Charlie, Willy Wonka, and the gang are sent hurtling through space and time. Visiting the world's first space hotel, battling the dreaded Vermicious Knids, and saving the world are only a few stops along this remarkable, intergalactic joyride. [SEP] childrens fantasy fiction children children-s
dcdc48c7d14a6467cf277c9c0919eb02   108999 1992-01-01 08:00:00+00:00                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         The Witches [SEP] This is not a fairy tale. This is about realwitches. Grandmamma loves to tell about witches. Real witches are the most dangerous of all living creatures on earth. There's nothing they hate so much as children, and they work all kinds of terrifying spells to get rid of them. Her grandson listens closely to Grandmamma's stories--but nothing can prepare him for the day he comes face-to-face with The Grand High Witch herself! [SEP] childrens fantasy fiction children children-s
dcdc48c7d14a6467cf277c9c0919eb02   299085 1992-01-01 08:00:00+00:00                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Goblins in the Castle [SEP] What moans at midnight in Toad-in-a-Cage Castle? Toad-in-a-Cage Castle was filled with secrets--secrets such as the hidden passages that led to every room, the long stairway that wound down to the dungeon, and the weird creature named Igor who lived there. But it was the mysterious night noises that bothered William the most--the strange moans that drifted through the halls of the castle where he was raised. He wanted to know what caused them. Then one night he found out.... [SEP] fantasy childrens children fiction young-adult
dcdc48c7d14a6467cf277c9c0919eb02    24178 1992-03-29 08:00:00+00:00                                                                                                                                                                                                                                                                                                                                                                                                                                                    Charlotte's Web [SEP] This beloved book by E. B. White, author of Stuart Little and The Trumpet of the Swan, is a classic of children's literature that is "just about perfect." Some Pig. Humble. Radiant. These are the words in Charlotte's Web, high up in Zuckerman's barn. Charlotte's spiderweb tells of her feelings for a little pig named Wilbur, who simply wants a friend. They also express the love of a girl named Fern, who saved Wilbur's life when he was born the runt of his litter. E. B. White's Newbery Honor Book is a tender novel of friendship, love, life, and death that will continue to be enjoyed by generations to come. This edition contains color illustrations by Garth Williams, the acclaimed illustrator of E.B. White's Stuart Little and Laura Ingalls Wilder's Little House series, among many other books. Supports the Common Core State Standards [SEP] classics childrens fiction children children-s
dcdc48c7d14a6467cf277c9c0919eb02  1248471 1995-01-01 08:00:00+00:00                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Walk Two Moons [SEP] young-adult fiction ya realistic-fiction childrens

In [ ]:
# --- Safely recreate item_semantic_embedding_static in books_df_cleaned using SentenceTransformer ---

from sentence_transformers import SentenceTransformer
import numpy as np

# 1. Rerun-safe: drop existing embedding column if present
if "item_semantic_embedding_static" in books_df_cleaned.columns:
    books_df_cleaned = books_df_cleaned.drop(columns=["item_semantic_embedding_static"])

# 2. Load embedding model once
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

# 3. Ensure text column is a clean string
books_df_cleaned["item_text_for_embedding"] = (
    books_df_cleaned["item_text_for_embedding"]
    .fillna("")
    .astype(str)
)

# 4. Encode text into dense semantic embeddings
item_embedding_matrix = embedding_model.encode(
    books_df_cleaned["item_text_for_embedding"].tolist(),
    batch_size=64,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
)

# 5. Store one embedding vector per row
books_df_cleaned["item_semantic_embedding_static"] = list(item_embedding_matrix)

# --- Summary / verification ---
num_nonempty = books_df_cleaned["item_text_for_embedding"].str.strip().ne("").sum()
total = len(books_df_cleaned)
embedding_dim = item_embedding_matrix.shape[1] if len(item_embedding_matrix) > 0 else 0

print(f"Rows with non-empty item_text_for_embedding: {num_nonempty} ({num_nonempty / total:.2%})")
print(f"Embedding dimension: {embedding_dim}")

sample_cols = [
    "book_id",
    "title",
    "item_text_for_embedding",
    "item_semantic_embedding_static",
]

print("\nSample of item_semantic_embedding_static in books_df_cleaned:")
print(
    books_df_cleaned[sample_cols]
    .head(5)
    .assign(
        item_semantic_embedding_static=lambda df: df["item_semantic_embedding_static"].apply(
            lambda x: np.array(x[:8]).round(4).tolist()
            if isinstance(x, (list, np.ndarray)) else x
        )
    )
    .to_string(index=False)
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/1939 [00:00<?, ?it/s]

In [ ]:
# --- Merge item_semantic_embedding_static into baseline_df and verify the merge ---

import numpy as np

# Drop existing column first to make reruns safe
if "item_semantic_embedding_static" in baseline_df.columns:
    baseline_df = baseline_df.drop(columns=["item_semantic_embedding_static"])

baseline_df = baseline_df.merge(
    books_df_cleaned[["book_id", "item_semantic_embedding_static"]],
    on="book_id",
    how="left",
    validate="many_to_one"
)

# --- Verification ---
has_embedding = baseline_df["item_semantic_embedding_static"].apply(
    lambda x: isinstance(x, (list, np.ndarray)) and len(x) > 0
).sum()

total = len(baseline_df)
print(f"Rows with non-empty item_semantic_embedding_static in baseline_df: {has_embedding} ({has_embedding / total:.2%})")

verify_cols = ["user_id", "book_id", "event_time", "item_semantic_embedding_static"]
verify_cols = [c for c in verify_cols if c in baseline_df.columns]

print("\nSample of merged item_semantic_embedding_static in baseline_df:")
print(
    baseline_df[verify_cols]
    .head(10)
    .assign(
        item_semantic_embedding_static=lambda df: df["item_semantic_embedding_static"].apply(
            lambda x: np.array(x[:8]).round(4).tolist()
            if isinstance(x, (list, np.ndarray)) else x
        )
    )
    .to_string(index=False)
)

Rows with non-empty item_embedding_static in baseline_df: 6384165 (100.00%)

Sample of merged item_embedding_static in baseline_df:
                         user_id  book_id                event_time                                                                                                                                                               item_embedding_static
00000377eea48021d3002730d56aca9a    13023 2014-12-07 20:11:06+00:00   [0.09489999711513519, -0.002199999988079071, 0.005900000222027302, 0.08089999854564667, -0.006800000090152025, -0.007400000002235174, 0.09229999780654907, 0.0052999998442828655]
00000377eea48021d3002730d56aca9a    41684 2014-12-07 20:13:38+00:00 [-0.06589999794960022, 0.10779999941587448, -0.060600001364946365, 0.10499999672174454, -0.0031999999191612005, -0.014000000432133675, -0.020099999383091927, -0.08980000019073486]
00000377eea48021d3002730d56aca9a    34268 2014-12-07 20:14:28+00:00   [0.005900000222027302, -0.000699999975040555, 0.049800001084804535, 0.008200000040233135, -0.07020000368356705, 0.029500000178813934, 0.047600001096725464, 0.002199999988079071]
00000377eea48021d3002730d56aca9a     3636 2014-12-07 20:15:18+00:00      [-0.059700001031160355, 0.08020000159740448, -0.02810000069439411, -0.05660000070929527, 0.016899999231100082, 0.0357000008225441, 0.01769999973475933, -0.010300000198185444]
00000377eea48021d3002730d56aca9a        5 2016-02-14 23:18:44+00:00     [0.0210999995470047, 0.02199999988079071, -0.0803999975323677, -0.011300000362098217, -0.049300000071525574, 0.0032999999821186066, 0.05380000174045563, -0.040800001472234726]
00004584d524ec468619e81b176cc991     3636 2013-04-06 01:22:29+00:00      [-0.059700001031160355, 0.08020000159740448, -0.02810000069439411, -0.05660000070929527, 0.016899999231100082, 0.0357000008225441, 0.01769999973475933, -0.010300000198185444]
00004584d524ec468619e81b176cc991   357664 2013-04-06 01:23:16+00:00        [-0.08649999648332596, -0.07999999821186066, 0.009100000374019146, 0.09239999949932098, -0.0215000007301569, 0.08479999750852585, 0.05420000106096268, 0.002300000051036477]
00004584d524ec468619e81b176cc991    38709 2013-04-06 01:23:56+00:00     [0.0010000000474974513, 0.07289999723434448, 0.006200000178068876, -0.0203000009059906, -0.024800000712275505, 0.023900000378489494, 0.0632999986410141, -0.021700000390410423]
00004584d524ec468619e81b176cc991   439173 2013-04-06 01:24:11+00:00    [-0.056699998676776886, -0.025699999183416367, 0.014999999664723873, 0.05849999934434891, -0.007799999788403511, -0.02239999920129776, 0.01360000018030405, 0.00430000014603138]
00004584d524ec468619e81b176cc991    13083 2013-04-06 01:24:19+00:00        [-0.08129999786615372, 0.06319999694824219, -0.06069999933242798, 0.016899999231100082, 0.1151999980211258, -0.04619999974966049, 0.060499999672174454, -0.0142000000923872]

User-Side Feature: User Behaviour before t

- num_pages_preference_gap - absolute difference between the current book’s num_pages and the user’s historical page preference before t
- user_hist_interaction_count_before_t
- days_since_user_last_interaction

In [ ]:
## num_pages_preference_gap

import numpy as np
import pandas as pd

# 0) Build lookup map from books_df_cleaned (no merge)
book_num_pages_map = books_df_cleaned.set_index("book_id")["num_pages"].to_dict()

# Safe rerun: drop/recreate helper + target feature columns on baseline_df
cols_to_drop = [
    "item_num_pages",
    "user_page_preference_before_t",
    "num_pages_preference_gap",
]
cols_to_drop = [c for c in cols_to_drop if c in baseline_df.columns]
if cols_to_drop:
    baseline_df = baseline_df.drop(columns=cols_to_drop)

# Add helper item attribute onto baseline_df via map
baseline_df["item_num_pages"] = baseline_df["book_id"].map(book_num_pages_map)

# 1) Ensure strict temporal ordering within user
baseline_df = baseline_df.sort_values(["user_id", "event_time", "book_id"]).reset_index(drop=True)

# 2) Initialize feature columns
baseline_df["user_page_preference_before_t"] = np.nan
baseline_df["num_pages_preference_gap"] = np.nan

# 3) Compute features user-by-user, row-by-row, using only prior rows
for user_id, idxs in baseline_df.groupby("user_id", sort=False).groups.items():
    prior_num_pages_sum = 0.0
    prior_num_pages_count = 0

    for idx in idxs:
        row = baseline_df.loc[idx]

        # Write current feature values using PRIOR state only
        if prior_num_pages_count > 0:
            user_page_pref = prior_num_pages_sum / prior_num_pages_count
            baseline_df.at[idx, "user_page_preference_before_t"] = user_page_pref

            curr_num_pages = row["item_num_pages"]
            if pd.notna(curr_num_pages):
                baseline_df.at[idx, "num_pages_preference_gap"] = abs(curr_num_pages - user_page_pref)

        # Update running state with CURRENT row after writing features
        curr_num_pages = row["item_num_pages"]
        if pd.notna(curr_num_pages):
            prior_num_pages_sum += curr_num_pages
            prior_num_pages_count += 1

# 4) Quick verification
feature_cols = [
    "user_id",
    "book_id",
    "event_time",
    "item_num_pages",
    "user_page_preference_before_t",
    "num_pages_preference_gap",
]
feature_cols = [c for c in feature_cols if c in baseline_df.columns]

print("\nSample of page-length preference features:")
print(baseline_df[feature_cols].head(20).to_string(index=False))

Sample of page-length preference features:
                         user_id  book_id                event_time  item_num_pages  is_read  user_page_preference_before_t  num_pages_preference_gap
00000377eea48021d3002730d56aca9a    13023 2014-12-07 20:11:06+00:00            92.0     True                            NaN                       NaN
00000377eea48021d3002730d56aca9a    41684 2014-12-07 20:13:38+00:00           368.0     True                      92.000000                276.000000
00000377eea48021d3002730d56aca9a    34268 2014-12-07 20:14:28+00:00             NaN     True                     230.000000                       NaN
00000377eea48021d3002730d56aca9a     3636 2014-12-07 20:15:18+00:00           208.0     True                     230.000000                 22.000000
00000377eea48021d3002730d56aca9a        5 2016-02-14 23:18:44+00:00           435.0     True                     222.666667                212.333333
00004584d524ec468619e81b176cc991     3636 2013-04-06 01:22:29+00:00           208.0     True                            NaN                       NaN
00004584d524ec468619e81b176cc991   357664 2013-04-06 01:23:16+00:00           182.0     True                     208.000000                 26.000000
00004584d524ec468619e81b176cc991    38709 2013-04-06 01:23:56+00:00           233.0     True                     195.000000                 38.000000
00004584d524ec468619e81b176cc991   439173 2013-04-06 01:24:11+00:00           105.0     True                     207.666667                102.666667
00004584d524ec468619e81b176cc991    13083 2013-04-06 01:24:19+00:00           292.0     True                     182.000000                110.000000
00004584d524ec468619e81b176cc991  1535111 2013-04-06 01:26:10+00:00           224.0     True                     204.000000                 20.000000
00004584d524ec468619e81b176cc991  4835838 2013-04-06 01:26:16+00:00           272.0     True                     207.333333                 64.666667
00004584d524ec468619e81b176cc991   235127 2013-04-06 01:26:18+00:00           160.0     True                     216.571429                 56.571429
00004584d524ec468619e81b176cc991  1653655 2013-04-06 01:26:30+00:00           256.0     True                     209.500000                 46.500000
00004584d524ec468619e81b176cc991  1258121 2013-04-06 01:26:32+00:00           192.0     True                     214.666667                 22.666667
00004584d524ec468619e81b176cc991  2540640 2013-04-06 01:26:42+00:00           320.0     True                     212.400000                107.600000
00004584d524ec468619e81b176cc991  8203202 2013-04-06 01:26:48+00:00           186.0     True                     222.181818                 36.181818
00004584d524ec468619e81b176cc991  6250208 2013-04-06 01:27:10+00:00           183.0     True                     219.166667                 36.166667
00004584d524ec468619e81b176cc991   825679 2013-04-06 01:27:35+00:00           144.0     True                     216.384615                 72.384615
00004584d524ec468619e81b176cc991  6696465 2013-04-06 01:27:43+00:00           304.0     True                     211.214286                 92.785714

Missingness summary:
user_page_preference_before_t     7.67% missing
num_pages_preference_gap         17.18% missing
dtype: object

In [ ]:
# --- Create user_hist_interaction_count_before_t on baseline_df (temporal, leakage-safe) ---

import pandas as pd
import numpy as np

# Safe rerun: drop existing column first
if "user_hist_interaction_count_before_t" in baseline_df.columns:
    baseline_df = baseline_df.drop(columns=["user_hist_interaction_count_before_t"])

# Ensure strict temporal ordering within user
baseline_df = baseline_df.sort_values(
    ["user_id", "event_time", "book_id"]
).reset_index(drop=True)

# Count prior interactions only
baseline_df["user_hist_interaction_count_before_t"] = (
    baseline_df.groupby("user_id").cumcount()
)

# Replace first interaction count 0 with NaN to exclude cold-start rows from segmentation
baseline_df["user_hist_interaction_count_before_t"] = baseline_df[
    "user_hist_interaction_count_before_t"
].replace(0, np.nan)

# --- Verification ---
verify_cols = [
    "user_id",
    "book_id",
    "event_time",
    "user_hist_interaction_count_before_t",
]
verify_cols = [c for c in verify_cols if c in baseline_df.columns]

print("\nSample of user_hist_interaction_count_before_t:")
print(baseline_df[verify_cols].head(20).to_string(index=False))

total = len(baseline_df)
num_missing = baseline_df["user_hist_interaction_count_before_t"].isna().sum()
num_sparse = (
    baseline_df["user_hist_interaction_count_before_t"].between(1, 4, inclusive="both")
).sum()
num_dense = (baseline_df["user_hist_interaction_count_before_t"] >= 5).sum()

print(f"\nRows with NaN (cold-start excluded): {num_missing} ({num_missing / total:.2%})")
print(f"Rows with sparse history (1-4): {num_sparse} ({num_sparse / total:.2%})")
print(f"Rows with dense history (>=5): {num_dense} ({num_dense / total:.2%})")

In [ ]:
# --- Create days_since_user_last_interaction on baseline_df (temporal, leakage-safe) ---

import numpy as np
import pandas as pd

# Safe rerun: drop existing column first
if "days_since_user_last_interaction" in baseline_df.columns:
    baseline_df = baseline_df.drop(columns=["days_since_user_last_interaction"])

# Ensure event_time is datetime
baseline_df["event_time"] = pd.to_datetime(baseline_df["event_time"], errors="coerce")

# Ensure strict temporal ordering within user
baseline_df = baseline_df.sort_values(
    ["user_id", "event_time", "book_id"]
).reset_index(drop=True)

# Previous interaction timestamp for the same user
baseline_df["prev_user_event_time"] = baseline_df.groupby("user_id")["event_time"].shift(1)

# Days since previous interaction
baseline_df["days_since_user_last_interaction"] = (
    baseline_df["event_time"] - baseline_df["prev_user_event_time"]
).dt.days

# Drop helper column to keep final table clean
baseline_df = baseline_df.drop(columns=["prev_user_event_time"])

# --- Verification ---
verify_cols = [
    "user_id",
    "book_id",
    "event_time",
    "days_since_user_last_interaction",
]
verify_cols = [c for c in verify_cols if c in baseline_df.columns]

print("\nSample of days_since_user_last_interaction:")
print(baseline_df[verify_cols].head(20).to_string(index=False))

total = len(baseline_df)
num_missing = baseline_df["days_since_user_last_interaction"].isna().sum()
num_nonmissing = baseline_df["days_since_user_last_interaction"].notna().sum()

print(f"\nRows with missing days_since_user_last_interaction: {num_missing} ({num_missing / total:.2%})")
print(f"Rows with non-missing days_since_user_last_interaction: {num_nonmissing} ({num_nonmissing / total:.2%})")

Item-Side Feature: Item Popularity
- book_interactions_count_before_t
- days_since_book_last_interaction

In [ ]:
# --- Create book_interactions_count_before_t on baseline_df (temporal, leakage-safe) ---

import pandas as pd

# Safe rerun: drop existing column first
if "book_interactions_count_before_t" in baseline_df.columns:
    baseline_df = baseline_df.drop(columns=["book_interactions_count_before_t"])

# Ensure strict temporal ordering across all rows
baseline_df = baseline_df.sort_values(
    ["event_time", "user_id", "book_id"]
).reset_index(drop=True)

# Count prior interactions for the same book only
baseline_df["book_interactions_count_before_t"] = (
    baseline_df.groupby("book_id").cumcount()
)

# --- Verification ---
verify_cols = [
    "user_id",
    "book_id",
    "event_time",
    "book_interactions_count_before_t",
]
verify_cols = [c for c in verify_cols if c in baseline_df.columns]

print("\nSample of book_interactions_count_before_t:")
print(baseline_df[verify_cols].head(20).to_string(index=False))

total = len(baseline_df)
num_zero = (baseline_df["book_interactions_count_before_t"] == 0).sum()
num_nonzero = (baseline_df["book_interactions_count_before_t"] > 0).sum()

print(f"\nRows with 0 prior book interactions: {num_zero} ({num_zero / total:.2%})")
print(f"Rows with >0 prior book interactions: {num_nonzero} ({num_nonzero / total:.2%})")

In [ ]:
# --- Create days_since_book_last_interaction on baseline_df (temporal, leakage-safe) ---

import pandas as pd

# Safe rerun: drop existing feature/helper columns first
cols_to_drop = [
    c for c in ["prev_book_event_time", "days_since_book_last_interaction"]
    if c in baseline_df.columns
]
if cols_to_drop:
    baseline_df = baseline_df.drop(columns=cols_to_drop)

# Ensure event_time is datetime
baseline_df["event_time"] = pd.to_datetime(baseline_df["event_time"], errors="coerce")

# Ensure strict temporal ordering across all rows
baseline_df = baseline_df.sort_values(
    ["event_time", "user_id", "book_id"]
).reset_index(drop=True)

# Previous interaction timestamp for the same book
baseline_df["prev_book_event_time"] = baseline_df.groupby("book_id")["event_time"].shift(1)

# Days since previous interaction of the same book
baseline_df["days_since_book_last_interaction"] = (
    baseline_df["event_time"] - baseline_df["prev_book_event_time"]
).dt.days

# Drop helper column to keep final table clean
baseline_df = baseline_df.drop(columns=["prev_book_event_time"])

# --- Verification ---
verify_cols = [
    "user_id",
    "book_id",
    "event_time",
    "days_since_book_last_interaction",
]
verify_cols = [c for c in verify_cols if c in baseline_df.columns]

print("\nSample of days_since_book_last_interaction:")
print(baseline_df[verify_cols].head(20).to_string(index=False))

total = len(baseline_df)
num_missing = baseline_df["days_since_book_last_interaction"].isna().sum()
num_nonmissing = baseline_df["days_since_book_last_interaction"].notna().sum()

print(f"\nRows with missing days_since_book_last_interaction: {num_missing} ({num_missing / total:.2%})")
print(f"Rows with non-missing days_since_book_last_interaction: {num_nonmissing} ({num_nonmissing / total:.2%})")

In [ ]:
print(f"Cols in baseline_df: {baseline_df.columns}")

Cols in baseline_df: Index(['user_id', 'book_id', 'review_id', 'event_time', 'cleaned_rating',
       'positive_rating', 'is_read', 'title', 'description',
       'has_meaningful_description', 'publication_year', 'num_pages',
       'language_code_collapsed', 'language_code_missing', 'format_collapsed',
       'is_ebook', 'authors_standardized', 'popular_shelves', 'ratings_count',
       'text_reviews_count', 'average_rating', 'main_author_id',
       'has_read_author_before_t', 'has_liked_author_before_t',
       'top_shelf_tags', 'item_text_for_embedding', 'item_embedding_static',
       'item_num_pages', 'user_page_preference_before_t',
       'num_pages_preference_gap', 'book_ratings_count_before_t',
       'book_average_rating_before_t', 'description_truncated'],
      dtype='object')

User-Side Feature: Author Affinity

- user_author_interaction_share_before_t
- user_hist_author_diversity_before_t

In [ ]:
# --- Create user_author_interaction_share_before_t on baseline_df (temporal, leakage-safe) ---

import numpy as np
import pandas as pd

# Safe rerun: drop existing column first
if "user_author_interaction_share_before_t" in baseline_df.columns:
    baseline_df = baseline_df.drop(columns=["user_author_interaction_share_before_t"])

# Ensure strict temporal ordering within user
baseline_df = baseline_df.sort_values(
    ["user_id", "event_time", "book_id"]
).reset_index(drop=True)

# Initialize feature column
baseline_df["user_author_interaction_share_before_t"] = np.nan

# Compute feature user-by-user using only prior rows
for user_id, idxs in baseline_df.groupby("user_id", sort=False).groups.items():
    total_prior_interactions = 0
    prior_author_counts = {}

    for idx in idxs:
        row = baseline_df.loc[idx]
        author_id = row["main_author_id"]

        # Write current row feature using PRIOR state only
        if total_prior_interactions > 0 and pd.notna(author_id):
            author_prior_count = prior_author_counts.get(author_id, 0)
            baseline_df.at[idx, "user_author_interaction_share_before_t"] = (
                author_prior_count / total_prior_interactions
            )

        # Update running state with CURRENT row after writing features
        if pd.notna(author_id):
            prior_author_counts[author_id] = prior_author_counts.get(author_id, 0) + 1

        total_prior_interactions += 1

# --- Verification ---
verify_cols = [
    "user_id",
    "book_id",
    "event_time",
    "main_author_id",
    "user_author_interaction_share_before_t",
]
verify_cols = [c for c in verify_cols if c in baseline_df.columns]

print("\nSample of user_author_interaction_share_before_t:")
print(baseline_df[verify_cols].head(20).to_string(index=False))

total = len(baseline_df)
num_missing = baseline_df["user_author_interaction_share_before_t"].isna().sum()
num_nonmissing = baseline_df["user_author_interaction_share_before_t"].notna().sum()

print(f"\nRows with missing user_author_interaction_share_before_t: {num_missing} ({num_missing / total:.2%})")
print(f"Rows with non-missing user_author_interaction_share_before_t: {num_nonmissing} ({num_nonmissing / total:.2%})")

In [ ]:
# --- Create user_hist_author_diversity_before_t on baseline_df (temporal, leakage-safe) ---

import pandas as pd
import numpy as np

# Safe rerun: drop existing column first
if "user_hist_author_diversity_before_t" in baseline_df.columns:
    baseline_df = baseline_df.drop(columns=["user_hist_author_diversity_before_t"])

# Ensure strict temporal ordering within user
baseline_df = baseline_df.sort_values(
    ["user_id", "event_time", "book_id"]
).reset_index(drop=True)

# Initialize feature column
baseline_df["user_hist_author_diversity_before_t"] = 0

# Compute feature user-by-user using only prior rows
for user_id, idxs in baseline_df.groupby("user_id", sort=False).groups.items():
    seen_authors = set()

    for idx in idxs:
        row = baseline_df.loc[idx]
        author_id = row["main_author_id"]

        # Write current row feature using PRIOR state only
        baseline_df.at[idx, "user_hist_author_diversity_before_t"] = len(seen_authors)

        # Update running state with CURRENT row after writing features
        if pd.notna(author_id):
            seen_authors.add(author_id)

# --- Verification ---
verify_cols = [
    "user_id",
    "book_id",
    "event_time",
    "main_author_id",
    "user_hist_author_diversity_before_t",
]
verify_cols = [c for c in verify_cols if c in baseline_df.columns]

print("\nSample of user_hist_author_diversity_before_t:")
print(baseline_df[verify_cols].head(20).to_string(index=False))

total = len(baseline_df)
num_zero = (baseline_df["user_hist_author_diversity_before_t"] == 0).sum()
num_positive = (baseline_df["user_hist_author_diversity_before_t"] > 0).sum()

print(f"\nRows with 0 prior author diversity: {num_zero} ({num_zero / total:.2%})")
print(f"Rows with >0 prior author diversity: {num_positive} ({num_positive / total:.2%})")

User Embedding
- user_profile_embedding_before_t
- user_profile_embedding_similarity

In [ ]:
# --- Create user_profile_embedding_before_t on baseline_df (temporal, leakage-safe) ---

import numpy as np
import pandas as pd

# Safe rerun: drop existing column first
if "user_profile_embedding_before_t" in baseline_df.columns:
    baseline_df = baseline_df.drop(columns=["user_profile_embedding_before_t"])

# Ensure strict temporal ordering within user
baseline_df = baseline_df.sort_values(
    ["user_id", "event_time", "book_id"]
).reset_index(drop=True)

# Find embedding dimension from the first valid item embedding
valid_item_embedding = next(
    (
        x for x in baseline_df["item_semantic_embedding_static"]
        if isinstance(x, (list, np.ndarray)) and len(x) > 0
    ),
    None
)

if valid_item_embedding is None:
    raise ValueError("No valid item_semantic_embedding_static found in baseline_df.")

embedding_dim = len(valid_item_embedding)

# Initialize output column
baseline_df["user_profile_embedding_before_t"] = pd.Series(
    [pd.NA] * len(baseline_df),
    dtype="object"
)

# Compute user profile embedding from prior interacted-item embeddings only
for user_id, idxs in baseline_df.groupby("user_id", sort=False).groups.items():
    running_sum = np.zeros(embedding_dim, dtype=float)
    running_count = 0

    for idx in idxs:
        row = baseline_df.loc[idx]
        curr_item_emb = row["item_semantic_embedding_static"]

        # Write current-row feature using PRIOR state only
        if running_count > 0:
            user_profile = running_sum / running_count

            # L2-normalize for consistency
            norm = np.linalg.norm(user_profile)
            if norm > 0:
                user_profile = user_profile / norm

            baseline_df.at[idx, "user_profile_embedding_before_t"] = user_profile

        # Update running state with CURRENT row after writing feature
        if isinstance(curr_item_emb, (list, np.ndarray)) and len(curr_item_emb) == embedding_dim:
            curr_item_emb = np.asarray(curr_item_emb, dtype=float)
            running_sum += curr_item_emb
            running_count += 1

# --- Verification ---
verify_cols = [
    "user_id",
    "book_id",
    "event_time",
    "user_profile_embedding_before_t",
]
verify_cols = [c for c in verify_cols if c in baseline_df.columns]

print("\nSample of user_profile_embedding_before_t:")
print(
    baseline_df[verify_cols]
    .head(10)
    .assign(
        user_profile_embedding_before_t=lambda df: df["user_profile_embedding_before_t"].apply(
            lambda x: np.array(x[:8]).round(4).tolist()
            if isinstance(x, (list, np.ndarray)) else x
        )
    )
    .to_string(index=False)
)

total = len(baseline_df)
num_missing = baseline_df["user_profile_embedding_before_t"].isna().sum()
num_nonmissing = baseline_df["user_profile_embedding_before_t"].notna().sum()

print(f"\nRows with missing user_profile_embedding_before_t: {num_missing} ({num_missing / total:.2%})")
print(f"Rows with non-missing user_profile_embedding_before_t: {num_nonmissing} ({num_nonmissing / total:.2%})")
print(f"Embedding dimension: {embedding_dim}")

In [ ]:
# --- Create user_profile_embedding_similarity on baseline_df ---

import numpy as np
import pandas as pd

# Safe rerun: drop existing column first
if "user_profile_embedding_similarity" in baseline_df.columns:
    baseline_df = baseline_df.drop(columns=["user_profile_embedding_similarity"])

def cosine_similarity_safe(a, b):
    if not isinstance(a, (list, np.ndarray)) or not isinstance(b, (list, np.ndarray)):
        return np.nan

    a = np.asarray(a, dtype=float)
    b = np.asarray(b, dtype=float)

    if a.size == 0 or b.size == 0 or a.shape != b.shape:
        return np.nan

    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)

    if norm_a == 0 or norm_b == 0:
        return np.nan

    return float(np.dot(a, b) / (norm_a * norm_b))

baseline_df["user_profile_embedding_similarity"] = baseline_df.apply(
    lambda row: cosine_similarity_safe(
        row["user_profile_embedding_before_t"],
        row["item_semantic_embedding_static"]
    ),
    axis=1
)

# --- Verification ---
verify_cols = [
    "user_id",
    "book_id",
    "event_time",
    "user_profile_embedding_similarity",
]
verify_cols = [c for c in verify_cols if c in baseline_df.columns]

print("\nSample of user_profile_embedding_similarity:")
print(baseline_df[verify_cols].head(20).to_string(index=False))

total = len(baseline_df)
num_missing = baseline_df["user_profile_embedding_similarity"].isna().sum()
num_nonmissing = baseline_df["user_profile_embedding_similarity"].notna().sum()

print(f"\nRows with missing user_profile_embedding_similarity: {num_missing} ({num_missing / total:.2%})")
print(f"Rows with non-missing user_profile_embedding_similarity: {num_nonmissing} ({num_nonmissing / total:.2%})")

if num_nonmissing > 0:
    print("\nSummary stats for user_profile_embedding_similarity:")
    print(baseline_df["user_profile_embedding_similarity"].describe())

<h1> Dropping Helper Columns </h1?

In [ ]:
# --- Keep only the final selected columns in baseline_df ---

# Columns to retain
cols_to_keep = [
    # Core IDs
    "user_id",
    "book_id",

    # Temporal tracking
    "event_time",

    # Static item metadata
    "title",
    "description_truncated",
    "top_shelf_tags",
    "has_meaningful_description",
    "publication_year",
    "num_pages",
    "language_code_collapsed",
    "format_collapsed",
    "is_ebook",
    "main_author_id",
    "item_semantic_embedding_static",

    # User-history / matching features
    "num_pages_preference_gap",
    "user_author_interaction_share_before_t",
    "user_profile_embedding_similarity",

    # Item temporal popularity
    "book_ratings_count_before_t",
    "book_average_rating_before_t",

    # User activity history
    "user_hist_interaction_count_before_t",
    "user_hist_author_diversity_before_t",
    "days_since_user_last_interaction",
]

# Keep only columns that actually exist in baseline_df
existing_cols_to_keep = [c for c in cols_to_keep if c in baseline_df.columns]

# Optional: show missing expected columns before subsetting
missing_cols = [c for c in cols_to_keep if c not in baseline_df.columns]
if missing_cols:
    print("These expected columns were not found in baseline_df and will be skipped:")
    for c in missing_cols:
        print(f"- {c}")

# Subset baseline_df to only the selected columns
baseline_df = baseline_df[existing_cols_to_keep].copy()

In [ ]:
print(f"Cols in baseline_df: {baseline_df.columns}")

<h1> Exporting </h1?

In [ ]:
baseline_df.to_pickle("baseline_df.pkl")
print("Exported baseline_df.pkl")

Exported baseline_df.pkl